export type Category = 'Air Cooling Miners' | 'Hydro Cooling Miners' | 'Immersion Miners'
export type Brand = 'MicroBT' | 'Bitmain' | 'IceRiver' | 'Goldshell' | 'Pinecone'
export type Cooling = 'air' | 'hydro'

export interface Product {
  slug: string
  title: string
  tag: string
  price: string
  priceUsd: number | null
  status?: 'In Stock' | 'No Stock'
  hashrate: string
  hashrateValue: number | null
  // Hashrate normalized to hashes-per-second, used only for cross-unit sort
  // comparisons (TH/s, GH/s, MH/s, and the ALEO/INI "M/s" and ZEC "KSol/s"
  // figures aren't directly comparable in their native units).
  hashrateHz: number | null
  power: string
  powerValue: number
  // Published-elsewhere power figure, when it differs from our own powerValue.
  powerWattsPublished?: number | null
  efficiency: string
  dailyProfit: string | null
  dailyProfitUsd: number | null
  payback: string | null
  media: { type: 'image' | 'video'; src: string }
  category: Category
  cooling: Cooling
  brand: Brand
  algorithm: string
  mineableCoins: { name: string; ticker: string }[]
  description: string
  specs: {
    manufacturer: string
    model: string
    release: string
    noiseLevel: string
    fans: string
    interface: string
    temperature: string
    humidity: string
  }
  dimensionsMm?: string | null
  weightKg?: number | null
  psuIncluded?: boolean | null
  sourceUrl?: string | null
  // Set when a listed spec couldn't be safely parsed/verified (see Whatsminer
  // M60 below) — needsReview items are excluded from every public listing.
  needsReview?: boolean
}

export const baseProducts: Product[] = [
  {
    slug: 'microbt-whatsminer-m66s-plus-318th',
    title: 'MicroBT WhatsMiner M66S+ (318TH)',
    tag: 'MICROBT',
    price: '$817',
    priceUsd: 817,
    status: 'In Stock',
    hashrate: '318 TH/s',
    hashrateValue: 318,
    hashrateHz: 318e12,
    power: '5,883 W',
    powerValue: 5883,
    efficiency: '18.5 J/TH',
    dailyProfit: '+$3.92',
    dailyProfitUsd: 3.92,
    payback: '954d',
    media: { type: 'image', src: '/asic/media/photo.png' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [
      { name: 'Bitcoin', ticker: 'BTC' },
      { name: 'Bitcoin Cash', ticker: 'BCH' },
    ],
    description:
      'The MicroBT WhatsMiner M66S+ (318TH) is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 318 TH/s with a power consumption of 5,883 W, offering an efficiency of 18.5 J/TH.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'MicroBT WhatsMiner M66S+ (318TH)',
      release: 'Latest Batch',
      noiseLevel: '75db',
      fans: '4',
      interface: 'Ethernet',
      temperature: '5 - 45 °C',
      humidity: '5 - 95 %',
    },
  },
  {
    slug: 'bitmain-antminer-s21-xp-270th',
    title: 'Bitmain Antminer S21 XP (270TH)',
    tag: 'BITMAIN',
    price: '$6,800',
    priceUsd: 6800,
    status: 'No Stock',
    hashrate: '270 TH/s',
    hashrateValue: 270,
    hashrateHz: 270e12,
    power: '3,645 W',
    powerValue: 3645,
    efficiency: '13.5 J/TH',
    dailyProfit: '+$8.10',
    dailyProfitUsd: 8.1,
    payback: '839d',
    media: { type: 'video', src: '/asic/media/video-1.webm' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [
      { name: 'Bitcoin', ticker: 'BTC' },
      { name: 'Bitcoin Cash', ticker: 'BCH' },
      { name: 'Bitcoin SV', ticker: 'BSV' },
    ],
    description:
      'The Bitmain Antminer S21 XP (270TH) is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 270 TH/s with a power consumption of 3,645 W, offering an efficiency of 13.5 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Bitmain Antminer S21 XP (270TH)',
      release: 'Jan 2026',
      noiseLevel: '75db',
      fans: '4',
      interface: 'Ethernet',
      temperature: '5 - 45 °C',
      humidity: '5 - 95 %',
    },
  },
  {
    slug: 'bitmain-antminer-s21-pro-plus-234th',
    title: 'Bitmain Antminer S21 Pro+ (234TH)',
    tag: 'BITMAIN',
    price: '$8,900',
    priceUsd: 8900,
    status: 'In Stock',
    hashrate: '234 TH/s',
    hashrateValue: 234,
    hashrateHz: 234e12,
    power: '3,510 W',
    powerValue: 3510,
    efficiency: '15.0 J/TH',
    dailyProfit: '+$11.20',
    dailyProfitUsd: 11.2,
    payback: '795d',
    media: { type: 'video', src: '/asic/media/video-2.webm' },
    category: 'Immersion Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [
      { name: 'Bitcoin', ticker: 'BTC' },
      { name: 'Bitcoin Cash', ticker: 'BCH' },
      { name: 'Bitcoin SV', ticker: 'BSV' },
    ],
    description:
      'The Bitmain Antminer S21 Pro+ (234TH) is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 234 TH/s with a power consumption of 3,510 W, offering an efficiency of 15.0 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Bitmain Antminer S21 Pro+ (234TH)',
      release: 'Latest Batch',
      noiseLevel: '76db',
      fans: '4',
      interface: 'Ethernet',
      temperature: '5 - 45 °C',
      humidity: '5 - 95 %',
    },
  },

  // --- Bulk catalogue import (46 machines) -------------------------------
  // Price is unknown for all of the below — "Contact for pricing" until real
  // figures are supplied. dailyProfit/payback are intentionally null: no
  // reliable live coin-price assumption exists for most of these coins, and
  // fabricating one would reintroduce the guaranteed-earnings problem this
  // catalogue was already cleaned of. These fields are never rendered
  // publicly regardless (see ProductsSection/ProductDetailPage).

  {
    slug: 'goldshell-ae-box-ii-54m',
    title: 'Goldshell AE BOX II 54 M/s',
    tag: 'GOLDSHELL',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '54 M/s',
    hashrateValue: 54,
    hashrateHz: 54e6,
    power: '530 W',
    powerValue: 530,
    efficiency: '9.8 J/M',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/goldshell-ae-box-ii-54m.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Goldshell',
    algorithm: 'zkSNARK',
    mineableCoins: [{ name: 'Aleo', ticker: 'ALEO' }],
    description:
      'The Goldshell AE BOX II 54 M/s is an ASIC miner designed for the zkSNARK algorithm. It delivers a hashrate of 54 M/s with a power consumption of 530 W, offering an efficiency of 9.8 J/M.',
    specs: {
      manufacturer: 'Goldshell',
      model: 'AE BOX II (54M)',
      release: 'Not specified',
      noiseLevel: '35db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '0 - 35 °C',
      humidity: '65 %',
    },
    dimensionsMm: '171 x 198 x 96',
    weightKg: 2.54,
    psuIncluded: false,
    sourceUrl: 'https://www.goldshell.com/product/goldshell-ae-box-ii/',
  },
  {
    slug: 'goldshell-ae-max-360m',
    title: 'Goldshell AE Max 360 M/s',
    tag: 'GOLDSHELL',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '360 M/s',
    hashrateValue: 360,
    hashrateHz: 360e6,
    power: '3,300 W',
    powerValue: 3300,
    efficiency: '9.2 J/M',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/goldshell-ae-max-360m.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Goldshell',
    algorithm: 'zkSNARK',
    mineableCoins: [{ name: 'Aleo', ticker: 'ALEO' }],
    description:
      'The Goldshell AE Max 360 M/s is an ASIC miner designed for the zkSNARK algorithm. It delivers a hashrate of 360 M/s with a power consumption of 3,300 W, offering an efficiency of 9.2 J/M. Source list carried both an unbranded "AE Max (360M)" row and a "Goldshell AE Max (360M)" row for this exact hashrate/power pair — merged into one record.',
    specs: {
      manufacturer: 'Goldshell',
      model: 'AE Max (360M)',
      release: 'Not specified',
      noiseLevel: '70db',
      fans: '4',
      interface: 'Ethernet',
      temperature: '5 - 45 °C',
      humidity: '5 - 65 %',
    },
    dimensionsMm: '264 x 200 x 290',
    weightKg: 13.5,
    psuIncluded: null,
    sourceUrl: 'https://asicmarketplace.com/product/goldshell-ae-max-aleo-miner/',
  },
  {
    slug: 'iceriver-ae1-lite-270m',
    title: 'IceRiver AE1 Lite 270 M/s',
    tag: 'ICERIVER',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '270 M/s',
    hashrateValue: 270,
    hashrateHz: 270e6,
    power: '500 W',
    powerValue: 500,
    efficiency: '1.9 J/M',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/iceriver-ae1-lite-270m.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'IceRiver',
    algorithm: 'zkSNARK',
    mineableCoins: [{ name: 'Aleo', ticker: 'ALEO' }],
    description:
      'The IceRiver AE1 Lite 270 M/s is an ASIC miner designed for the zkSNARK algorithm. It delivers a hashrate of 270 M/s with a power consumption of 500 W, offering an efficiency of 1.9 J/M. Brand inferred from the separate "Iceriver AE1 Lite (300M)" listing — the source did not prefix this row with a brand. Physical specs assumed shared with the 300M variant (same chassis, different factory bin); please verify before publishing.',
    specs: {
      manufacturer: 'IceRiver',
      model: 'AE1 Lite (270M)',
      release: 'Apr 2025',
      noiseLevel: '45db',
      fans: '1',
      interface: 'Ethernet',
      temperature: '5 - 40 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '298 x 208 x 304',
    weightKg: 4.69,
    psuIncluded: null,
    sourceUrl: 'https://www.iceriver.io/product/iceriver-aleo-ae1-lite/',
  },
  {
    slug: 'iceriver-ae1-lite-300m',
    title: 'IceRiver AE1 Lite 300 M/s',
    tag: 'ICERIVER',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '300 M/s',
    hashrateValue: 300,
    hashrateHz: 300e6,
    power: '500 W',
    powerValue: 500,
    efficiency: '1.7 J/M',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/iceriver-ae1-lite-300m.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'IceRiver',
    algorithm: 'zkSNARK',
    mineableCoins: [{ name: 'Aleo', ticker: 'ALEO' }],
    description:
      'The IceRiver AE1 Lite 300 M/s is an ASIC miner designed for the zkSNARK algorithm. It delivers a hashrate of 300 M/s with a power consumption of 500 W, offering an efficiency of 1.7 J/M.',
    specs: {
      manufacturer: 'IceRiver',
      model: 'AE1 Lite (300M)',
      release: 'Apr 2025',
      noiseLevel: '45db',
      fans: '1',
      interface: 'Ethernet',
      temperature: '5 - 40 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '298 x 208 x 304',
    weightKg: 4.69,
    psuIncluded: null,
    sourceUrl: 'https://www.iceriver.io/product/iceriver-aleo-ae1-lite/',
  },
  {
    slug: 'bitmain-antminer-al1-16-6t',
    title: 'Bitmain Antminer AL1 16.6 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '16.6 TH/s',
    hashrateValue: 16.6,
    hashrateHz: 16.6e12,
    power: '3,730 W',
    powerValue: 3730,
    efficiency: '224.7 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-al1-16-6t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Blake3',
    mineableCoins: [{ name: 'Alephium', ticker: 'ALPH' }],
    description:
      'The Bitmain Antminer AL1 16.6 TH/s is a high-performance ASIC miner designed for the Blake3 algorithm. It delivers a hashrate of 16.6 TH/s with a power consumption of 3,730 W, offering an efficiency of 224.7 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer AL1 16.6T',
      release: 'Sep 2024',
      noiseLevel: '75db',
      fans: '4',
      interface: 'Ethernet',
      temperature: '5 - 45 °C',
      humidity: '5 - 95 %',
    },
    dimensionsMm: '400 x 195 x 290',
    weightKg: 13.6,
    psuIncluded: null,
    sourceUrl: 'https://viperatech.com/product/bitmain-antminer-al1-pro-16-6th-s-3730w-alph',
  },
  {
    slug: 'bitmain-antminer-e9-2400m',
    title: 'Bitmain Antminer E9 2400 MH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '2400 MH/s',
    hashrateValue: 2400,
    hashrateHz: 2400e6,
    power: '2,013 W',
    powerValue: 2013,
    efficiency: '0.8 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-e9-2400m.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'EtHash',
    mineableCoins: [{ name: 'Ethereum Classic', ticker: 'ETC' }],
    description:
      'The Bitmain Antminer E9 2400 MH/s is an ASIC miner designed for the EtHash algorithm. It delivers a hashrate of 2400 MH/s with a power consumption of 2,013 W, offering an efficiency of 0.8 J/MH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer E9 (2400M)',
      release: 'Jul 2022',
      noiseLevel: '75db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: 'Not specified',
      humidity: 'Not specified',
    },
    dimensionsMm: '400 x 290 x 195',
    weightKg: 14.2,
    psuIncluded: null,
    sourceUrl: 'https://www.cryptominerbros.com/product/bitmain-antminer-e9-3gh-s-ethereum-miner/',
  },
  {
    slug: 'bitmain-antminer-e9-pro-3680m',
    title: 'Bitmain Antminer E9 Pro 3680 MH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '3680 MH/s',
    hashrateValue: 3680,
    hashrateHz: 3680e6,
    power: '2,200 W',
    powerValue: 2200,
    efficiency: '0.6 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-e9-pro-3680m.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'EtHash',
    mineableCoins: [{ name: 'Ethereum Classic', ticker: 'ETC' }],
    description:
      'The Bitmain Antminer E9 Pro 3680 MH/s is an ASIC miner designed for the EtHash algorithm. It delivers a hashrate of 3680 MH/s with a power consumption of 2,200 W, offering an efficiency of 0.6 J/MH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer E9 Pro (3680M)',
      release: 'Not specified',
      noiseLevel: '75db',
      fans: '4',
      interface: 'Ethernet',
      temperature: 'Not specified',
      humidity: 'Not specified',
    },
    dimensionsMm: '550 x 195 x 310',
    weightKg: 20.2,
    psuIncluded: null,
    sourceUrl: 'https://asicmarketplace.com/product/bitmain-antminer-e9-pro-etc-miner-3-68gh/',
  },
  {
    slug: 'bitmain-antminer-ks3-8-2t',
    title: 'Bitmain Antminer KS3 8.2 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '8.2 TH/s',
    hashrateValue: 8.2,
    hashrateHz: 8.2e12,
    power: '3,200 W',
    powerValue: 3200,
    efficiency: '390.2 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-ks3-8-2t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'KHeavyHash',
    mineableCoins: [{ name: 'Kaspa', ticker: 'KAS' }],
    description:
      'The Bitmain Antminer KS3 8.2 TH/s is an ASIC miner designed for the KHeavyHash algorithm. It delivers a hashrate of 8.2 TH/s with a power consumption of 3,200 W, offering an efficiency of 390.2 J/TH. Physical specs assumed shared with the KS3 9.4T bin of the same chassis.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer KS3 (8.2T)',
      release: 'Not specified',
      noiseLevel: '75db',
      fans: '4',
      interface: 'Ethernet',
      temperature: '0 - 40 °C',
      humidity: '10 - 90 %',
    },
    dimensionsMm: '430 x 195 x 290',
    weightKg: 16.1,
    psuIncluded: null,
    sourceUrl: 'https://asicmarketplace.com/blog/bitmain-antminer-ks3-overview/',
  },
  {
    slug: 'bitmain-antminer-ks3-9-4t',
    title: 'Bitmain Antminer KS3 9.4 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '9.4 TH/s',
    hashrateValue: 9.4,
    hashrateHz: 9.4e12,
    power: '3,500 W',
    powerValue: 3500,
    efficiency: '372.3 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-ks3-9-4t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'KHeavyHash',
    mineableCoins: [{ name: 'Kaspa', ticker: 'KAS' }],
    description:
      'The Bitmain Antminer KS3 9.4 TH/s is an ASIC miner designed for the KHeavyHash algorithm. It delivers a hashrate of 9.4 TH/s with a power consumption of 3,500 W, offering an efficiency of 372.3 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer KS3-9.4T',
      release: 'Not specified',
      noiseLevel: '75db',
      fans: '4',
      interface: 'Ethernet',
      temperature: '0 - 40 °C',
      humidity: '10 - 90 %',
    },
    dimensionsMm: '430 x 195 x 290',
    weightKg: 16.1,
    psuIncluded: null,
    sourceUrl: 'https://asicmarketplace.com/blog/bitmain-antminer-ks3-overview/',
  },
  {
    slug: 'bitmain-antminer-ks5-pro-21t',
    title: 'Bitmain Antminer KS5 Pro 21 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '21 TH/s',
    hashrateValue: 21,
    hashrateHz: 21e12,
    power: '3,150 W',
    powerValue: 3150,
    efficiency: '150.0 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-ks5-pro-21t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'KHeavyHash',
    mineableCoins: [{ name: 'Kaspa', ticker: 'KAS' }],
    description:
      'The Bitmain Antminer KS5 Pro 21 TH/s is an ASIC miner designed for the KHeavyHash algorithm. It delivers a hashrate of 21 TH/s with a power consumption of 3,150 W, offering an efficiency of 150.0 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer KS5 Pro (21T)',
      release: 'Not specified',
      noiseLevel: '76db',
      fans: '4',
      interface: 'Ethernet',
      temperature: '0 - 40 °C',
      humidity: '10 - 90 %',
    },
    dimensionsMm: '430 x 195 x 290',
    weightKg: 15.8,
    psuIncluded: null,
    sourceUrl: 'https://asicmarketplace.com/product/bitmain-antminer-ks5-pro-kaspa-miner/',
  },
  {
    slug: 'bitmain-antminer-l11-20g',
    title: 'Bitmain Antminer L11 20 GH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '20 GH/s',
    hashrateValue: 20,
    hashrateHz: 20e9,
    power: '3,680 W',
    powerValue: 3680,
    efficiency: '0.2 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-l11-20g.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [
      { name: 'Dogecoin', ticker: 'DOGE' },
      { name: 'Litecoin', ticker: 'LTC' },
    ],
    description:
      'The Bitmain Antminer L11 20 GH/s is a high-performance ASIC miner designed for the Scrypt algorithm. It delivers a hashrate of 20 GH/s with a power consumption of 3,680 W, offering an efficiency of 0.2 J/MH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L11 20G',
      release: 'Not specified',
      noiseLevel: '75db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: 'Not specified',
      humidity: 'Not specified',
    },
    dimensionsMm: '400 x 195 x 290',
    weightKg: 15.5,
    psuIncluded: null,
    sourceUrl: 'https://apextomining.com/2025/09/04/bitmain-antminer-l11-series-miners-most-powerful-dogecoin-litecoin-miners/',
  },
  {
    slug: 'bitmain-antminer-l7-9050m',
    title: 'Bitmain Antminer L7 9050 MH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '9050 MH/s',
    hashrateValue: 9050,
    hashrateHz: 9050e6,
    power: '3,425 W',
    powerValue: 3425,
    efficiency: '0.4 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-l7-9050m.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [
      { name: 'Dogecoin', ticker: 'DOGE' },
      { name: 'Litecoin', ticker: 'LTC' },
    ],
    description:
      'The Bitmain Antminer L7 9050 MH/s is a high-performance ASIC miner designed for the Scrypt algorithm. It delivers a hashrate of 9050 MH/s with a power consumption of 3,425 W, offering an efficiency of 0.4 J/MH. Physical specs assumed shared across all L7 hashrate bins (9050M/9300M/9500M) — same chassis.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L7 (9050M)',
      release: 'Not specified',
      noiseLevel: '75db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '0 - 40 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '370 x 195 x 290',
    weightKg: 15,
    psuIncluded: null,
    sourceUrl: 'https://www.bigskyasics.com/shop/bitmain-antminer-l7-9050mh/',
  },
  {
    slug: 'bitmain-antminer-l7-9300m',
    title: 'Bitmain Antminer L7 9300 MH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '9300 MH/s',
    hashrateValue: 9300,
    hashrateHz: 9300e6,
    power: '3,425 W',
    powerValue: 3425,
    efficiency: '0.4 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-l7-9300m.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [
      { name: 'Dogecoin', ticker: 'DOGE' },
      { name: 'Litecoin', ticker: 'LTC' },
    ],
    description:
      'The Bitmain Antminer L7 9300 MH/s is a high-performance ASIC miner designed for the Scrypt algorithm. It delivers a hashrate of 9300 MH/s with a power consumption of 3,425 W, offering an efficiency of 0.4 J/MH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L7 (9300M)',
      release: 'Not specified',
      noiseLevel: '75db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '0 - 40 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '370 x 195 x 290',
    weightKg: 15,
    psuIncluded: null,
    sourceUrl: 'https://www.bigskyasics.com/shop/bitmain-antminer-l7-9050mh/',
  },
  {
    slug: 'bitmain-antminer-l7-9500m',
    title: 'Bitmain Antminer L7 9500 MH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '9500 MH/s',
    hashrateValue: 9500,
    hashrateHz: 9500e6,
    power: '3,425 W',
    powerValue: 3425,
    efficiency: '0.4 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-l7-9500m.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [
      { name: 'Dogecoin', ticker: 'DOGE' },
      { name: 'Litecoin', ticker: 'LTC' },
    ],
    description:
      'The Bitmain Antminer L7 9500 MH/s is a high-performance ASIC miner designed for the Scrypt algorithm. It delivers a hashrate of 9500 MH/s with a power consumption of 3,425 W, offering an efficiency of 0.4 J/MH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L7 (9500M)',
      release: 'Not specified',
      noiseLevel: '75db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '0 - 40 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '370 x 195 x 290',
    weightKg: 15,
    psuIncluded: null,
    sourceUrl: 'https://www.bigskyasics.com/shop/bitmain-antminer-l7-9050mh/',
  },
  {
    slug: 'bitmain-antminer-l9-15g',
    title: 'Bitmain Antminer L9 15 GH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '15 GH/s',
    hashrateValue: 15,
    hashrateHz: 15e9,
    power: '3,150 W',
    powerValue: 3150,
    efficiency: '0.2 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-l9-15g.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [
      { name: 'Dogecoin', ticker: 'DOGE' },
      { name: 'Litecoin', ticker: 'LTC' },
    ],
    description:
      'The Bitmain Antminer L9 15 GH/s is a high-performance ASIC miner designed for the Scrypt algorithm. It delivers a hashrate of 15 GH/s with a power consumption of 3,150 W, offering an efficiency of 0.2 J/MH. Physical specs assumed shared across all L9 hashrate bins (15G/16G/16.5G/17G) — same chassis.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L9 15G',
      release: 'May 2024',
      noiseLevel: '75db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: 'Not specified',
      humidity: 'Not specified',
    },
    dimensionsMm: '379 x 290 x 195',
    weightKg: 13.5,
    psuIncluded: null,
    sourceUrl: 'https://www.simplemining.io/insights/post/antminer-l9-review',
  },
  {
    slug: 'bitmain-antminer-l9-16g',
    title: 'Bitmain Antminer L9 16 GH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '16 GH/s',
    hashrateValue: 16,
    hashrateHz: 16e9,
    power: '3,360 W',
    powerValue: 3360,
    efficiency: '0.2 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-l9-16g.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [
      { name: 'Dogecoin', ticker: 'DOGE' },
      { name: 'Litecoin', ticker: 'LTC' },
    ],
    description:
      'The Bitmain Antminer L9 16 GH/s is a high-performance ASIC miner designed for the Scrypt algorithm. It delivers a hashrate of 16 GH/s with a power consumption of 3,360 W, offering an efficiency of 0.2 J/MH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L9 16G',
      release: 'May 2024',
      noiseLevel: '75db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: 'Not specified',
      humidity: 'Not specified',
    },
    dimensionsMm: '379 x 290 x 195',
    weightKg: 13.5,
    psuIncluded: null,
    sourceUrl: 'https://www.simplemining.io/insights/post/antminer-l9-review',
  },
  {
    slug: 'bitmain-antminer-l9-16-5g',
    title: 'Bitmain Antminer L9 16.5 GH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '16.5 GH/s',
    hashrateValue: 16.5,
    hashrateHz: 16.5e9,
    power: '3,460 W',
    powerValue: 3460,
    efficiency: '0.2 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-l9-16-5g.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [
      { name: 'Dogecoin', ticker: 'DOGE' },
      { name: 'Litecoin', ticker: 'LTC' },
    ],
    description:
      'The Bitmain Antminer L9 16.5 GH/s is a high-performance ASIC miner designed for the Scrypt algorithm. It delivers a hashrate of 16.5 GH/s with a power consumption of 3,460 W, offering an efficiency of 0.2 J/MH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L9 16.5G',
      release: 'May 2024',
      noiseLevel: '75db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: 'Not specified',
      humidity: 'Not specified',
    },
    dimensionsMm: '379 x 290 x 195',
    weightKg: 13.5,
    psuIncluded: null,
    sourceUrl: 'https://www.simplemining.io/insights/post/antminer-l9-review',
  },
  {
    slug: 'bitmain-antminer-l9-17g',
    title: 'Bitmain Antminer L9 17 GH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '17 GH/s',
    hashrateValue: 17,
    hashrateHz: 17e9,
    power: '3,570 W',
    powerValue: 3570,
    efficiency: '0.2 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-l9-17g.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [
      { name: 'Dogecoin', ticker: 'DOGE' },
      { name: 'Litecoin', ticker: 'LTC' },
    ],
    description:
      'The Bitmain Antminer L9 17 GH/s is a high-performance ASIC miner designed for the Scrypt algorithm. It delivers a hashrate of 17 GH/s with a power consumption of 3,570 W, offering an efficiency of 0.2 J/MH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L9 17G',
      release: 'May 2024',
      noiseLevel: '75db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: 'Not specified',
      humidity: 'Not specified',
    },
    dimensionsMm: '379 x 290 x 195',
    weightKg: 13.5,
    psuIncluded: null,
    sourceUrl: 'https://www.simplemining.io/insights/post/antminer-l9-review',
  },
  {
    slug: 'bitmain-antminer-s19-pro-100t',
    title: 'Bitmain Antminer S19 Pro 100 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '100 TH/s',
    hashrateValue: 100,
    hashrateHz: 100e12,
    power: '3,050 W',
    powerValue: 3050,
    efficiency: '30.5 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s19-pro-100t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer S19 Pro 100 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 100 TH/s with a power consumption of 3,050 W, offering an efficiency of 30.5 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19 Pro (100T)',
      release: 'May 2020',
      noiseLevel: '75db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: 'Not specified',
      humidity: 'Not specified',
    },
    dimensionsMm: '370 x 195.5 x 290',
    weightKg: 13.2,
    psuIncluded: null,
    sourceUrl: 'https://d-central.tech/miners/antminer-s19j-pro-104th/',
  },
  {
    slug: 'bitmain-antminer-s19-pro-104t',
    title: 'Bitmain Antminer S19 Pro 104 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '104 TH/s',
    hashrateValue: 104,
    hashrateHz: 104e12,
    power: '3,068 W',
    powerValue: 3068,
    efficiency: '29.5 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s19-pro-104t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer S19 Pro 104 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 104 TH/s with a power consumption of 3,068 W, offering an efficiency of 29.5 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19 Pro (104T)',
      release: 'May 2020',
      noiseLevel: '75db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: 'Not specified',
      humidity: 'Not specified',
    },
    dimensionsMm: '370 x 195.5 x 290',
    weightKg: 13.2,
    psuIncluded: null,
    sourceUrl: 'https://d-central.tech/miners/antminer-s19j-pro-104th/',
  },
  {
    slug: 'bitmain-antminer-s19-xp-141t',
    title: 'Bitmain Antminer S19 XP 141 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '141 TH/s',
    hashrateValue: 141,
    hashrateHz: 141e12,
    power: '3,010 W',
    powerValue: 3010,
    efficiency: '21.3 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s19-xp-141t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer S19 XP 141 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 141 TH/s with a power consumption of 3,010 W, offering an efficiency of 21.3 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19 XP (141T)',
      release: 'Dec 2022',
      noiseLevel: 'Not specified',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '5 - 45 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: null,
    weightKg: null,
    psuIncluded: null,
    sourceUrl: 'https://support.bitmain.com/hc/en-us/articles/8906244096409-S19-XP-Specifications',
  },
  {
    slug: 'bitmain-antminer-s19j-pro-100t',
    title: 'Bitmain Antminer S19j Pro 100 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '100 TH/s',
    hashrateValue: 100,
    hashrateHz: 100e12,
    power: '3,050 W',
    powerValue: 3050,
    efficiency: '30.5 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s19j-pro-100t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer S19j Pro 100 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 100 TH/s with a power consumption of 3,050 W, offering an efficiency of 30.5 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19j Pro (100T)',
      release: 'Jul 2021',
      noiseLevel: '75db',
      fans: '4',
      interface: 'Ethernet',
      temperature: 'Not specified',
      humidity: 'Not specified',
    },
    dimensionsMm: '400 x 195 x 290',
    weightKg: 13.2,
    psuIncluded: null,
    sourceUrl: 'https://d-central.tech/miners/antminer-s19j-pro/',
  },
  {
    slug: 'bitmain-antminer-s19j-pro-104t',
    title: 'Bitmain Antminer S19j Pro 104 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '104 TH/s',
    hashrateValue: 104,
    hashrateHz: 104e12,
    power: '3,068 W',
    powerValue: 3068,
    efficiency: '29.5 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s19j-pro-104t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer S19j Pro 104 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 104 TH/s with a power consumption of 3,068 W, offering an efficiency of 29.5 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19j Pro (104T)',
      release: 'Jul 2021',
      noiseLevel: '75db',
      fans: '4',
      interface: 'Ethernet',
      temperature: 'Not specified',
      humidity: 'Not specified',
    },
    dimensionsMm: '400 x 195 x 290',
    weightKg: 13.2,
    psuIncluded: null,
    sourceUrl: 'https://d-central.tech/miners/antminer-s19j-pro-104th/',
  },
  {
    slug: 'bitmain-antminer-s19j-pro-plus-120t',
    title: 'Bitmain Antminer S19j Pro+ 120 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '120 TH/s',
    hashrateValue: 120,
    hashrateHz: 120e12,
    power: '3,300 W',
    powerValue: 3300,
    efficiency: '27.5 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s19j-pro-plus-120t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer S19j Pro+ 120 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 120 TH/s with a power consumption of 3,300 W, offering an efficiency of 27.5 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19j Pro+ (120T)',
      release: 'Not specified',
      noiseLevel: '75db',
      fans: '4',
      interface: 'Ethernet',
      temperature: '5 - 45 °C',
      humidity: '5 - 95 %',
    },
    dimensionsMm: '400 x 195 x 290',
    weightKg: 13.7,
    psuIncluded: null,
    sourceUrl: 'https://miningnow.com/asic-miner/bitmain-antminer-s19j-pro-plus-120th-s/',
  },
  {
    slug: 'bitmain-antminer-s21-195t',
    title: 'Bitmain Antminer S21 195 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '195 TH/s',
    hashrateValue: 195,
    hashrateHz: 195e12,
    power: '3,500 W',
    powerValue: 3500,
    efficiency: '17.9 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s21-195t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer S21 195 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 195 TH/s with a power consumption of 3,500 W, offering an efficiency of 17.9 J/TH. Physical specs assumed shared with the 200T bin of the same chassis.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21 (195T)',
      release: 'Not specified',
      noiseLevel: '75db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '5 - 45 °C',
      humidity: '5 - 95 %',
    },
    dimensionsMm: '400 x 195 x 290',
    weightKg: 14.2,
    psuIncluded: null,
    sourceUrl: 'https://viperatech.com/product/bitmain-antminer-s21-195th-s-3500w',
  },
  {
    slug: 'bitmain-antminer-s21-200t',
    title: 'Bitmain Antminer S21 200 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '200 TH/s',
    hashrateValue: 200,
    hashrateHz: 200e12,
    power: '3,550 W',
    powerValue: 3550,
    efficiency: '17.8 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s21-200t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer S21 200 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 200 TH/s with a power consumption of 3,550 W, offering an efficiency of 17.8 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21 (200T)',
      release: 'Not specified',
      noiseLevel: '75db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '5 - 45 °C',
      humidity: '5 - 95 %',
    },
    dimensionsMm: '400 x 195 x 290',
    weightKg: 14.2,
    psuIncluded: null,
    sourceUrl: 'https://viperatech.com/product/bitmain-antminer-s21-200th-s-3500w',
  },
  {
    slug: 'bitmain-antminer-s21-pro-234t',
    title: 'Bitmain Antminer S21 Pro 234 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '234 TH/s',
    hashrateValue: 234,
    hashrateHz: 234e12,
    power: '3,510 W',
    powerValue: 3510,
    efficiency: '15.0 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s21-pro-234t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      "The Bitmain Antminer S21 Pro 234 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 234 TH/s with a power consumption of 3,510 W, offering an efficiency of 15.0 J/TH. Bitmain's official S21 Pro spec page headlines the 245T/3675W bin — dimensions/weight/noise below are shared from that page under the assumption both bins share one chassis.",
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21 Pro (234T)',
      release: 'Not specified',
      noiseLevel: '76db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '-20 - 45 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '450 x 219 x 293',
    weightKg: 18.5,
    psuIncluded: null,
    sourceUrl: 'https://support.bitmain.com/hc/en-us/articles/31321354157593-S21-Pro-Specification',
  },
  {
    slug: 'bitmain-antminer-s21-pro-245th',
    title: 'Bitmain Antminer S21 Pro 245 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '245 TH/s',
    hashrateValue: 245,
    hashrateHz: 245e12,
    power: '3,510 W',
    powerValue: 3510,
    powerWattsPublished: 3675,
    efficiency: '14.3 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s21-pro-245th.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer S21 Pro 245 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 245 TH/s with a power consumption of 3,510 W, offering an efficiency of 14.3 J/TH. FLAG: Bitmain officially publishes this exact bin (245T) at 3675W (14.3 does not match Bitmain\'s official 15 J/TH for this bin) — our source list gives 3,510 W for it. See powerKwPublished.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21 Pro (245Th)',
      release: 'Not specified',
      noiseLevel: '76db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '-20 - 45 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '450 x 219 x 293',
    weightKg: 18.5,
    psuIncluded: null,
    sourceUrl: 'https://support.bitmain.com/hc/en-us/articles/31321354157593-S21-Pro-Specification',
  },
  {
    slug: 'bitmain-antminer-s21-xp-270t',
    title: 'Bitmain Antminer S21 XP 270 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '270 TH/s',
    hashrateValue: 270,
    hashrateHz: 270e12,
    power: '3,645 W',
    powerValue: 3645,
    efficiency: '13.5 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s21-xp-270t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer S21 XP 270 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 270 TH/s with a power consumption of 3,645 W, offering an efficiency of 13.5 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21 XP (270T)',
      release: 'Jul 2024',
      noiseLevel: '76db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '-20 - 45 °C',
      humidity: '10 - 90 %',
    },
    dimensionsMm: '449 x 219 x 293',
    weightKg: 18.7,
    psuIncluded: null,
    sourceUrl: 'https://support.bitmain.com/hc/en-us/articles/35383015643673-S21-XP-Specifications',
  },
  {
    slug: 'bitmain-antminer-s21-xp-hydro-473t',
    title: 'Bitmain Antminer S21 XP Hydro 473 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '473 TH/s',
    hashrateValue: 473,
    hashrateHz: 473e12,
    power: '5,676 W',
    powerValue: 5676,
    efficiency: '12.0 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s21-xp-hydro-473t.svg' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer S21 XP Hydro 473 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 473 TH/s with a power consumption of 5,676 W, offering an efficiency of 12.0 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21 XP Hydro (473T)',
      release: 'Not specified',
      noiseLevel: '50db',
      fans: 'Liquid-cooled',
      interface: 'Ethernet',
      temperature: '5 - 45 °C',
      humidity: '5 - 95 %',
    },
    dimensionsMm: '410 x 170 x 209',
    weightKg: 12.8,
    psuIncluded: null,
    sourceUrl: 'https://support.bitmain.com/hc/en-us/articles/34523540504857-S21-XP-Hyd-Specification',
  },
  {
    slug: 'bitmain-antminer-s21-plus-216t',
    title: 'Bitmain Antminer S21+ 216 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '216 TH/s',
    hashrateValue: 216,
    hashrateHz: 216e12,
    power: '3,564 W',
    powerValue: 3564,
    efficiency: '16.5 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s21-plus-216t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer S21+ 216 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 216 TH/s with a power consumption of 3,564 W, offering an efficiency of 16.5 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21+ (216T)',
      release: 'Not specified',
      noiseLevel: '76db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '-5 - 40 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '450 x 219 x 293',
    weightKg: 22.9,
    psuIncluded: null,
    sourceUrl: 'https://miningnow.com/asic-miner/bitmain-antminer-s21-plus-216th-s/',
  },
  {
    slug: 'bitmain-antminer-s21-plus-hyd-338t',
    title: 'Bitmain Antminer S21+ Hyd 338 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '338 TH/s',
    hashrateValue: 338,
    hashrateHz: 338e12,
    power: '5,070 W',
    powerValue: 5070,
    efficiency: '15.0 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s21-plus-hyd-338t.svg' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer S21+ Hyd 338 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 338 TH/s with a power consumption of 5,070 W, offering an efficiency of 15.0 J/TH. Physical specs assumed shared across the S21+ hydro bins (338T/358T/395T) — same liquid-cooled chassis.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21+ Hyd (338T)',
      release: 'Not specified',
      noiseLevel: 'Not specified (liquid-cooled)',
      fans: 'Liquid-cooled',
      interface: 'Ethernet',
      temperature: 'Coolant inlet 20 - 50 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '339 x 173 x 207',
    weightKg: 14.5,
    psuIncluded: null,
    sourceUrl: 'https://www.unistarminer.com/products/bitmain-antminer-bitcoin-miner-s21-hyd-358t-395t-unistar',
  },
  {
    slug: 'bitmain-antminer-s21-plus-hydro-358t',
    title: 'Bitmain Antminer S21+ Hydro 358 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '358 TH/s',
    hashrateValue: 358,
    hashrateHz: 358e12,
    power: '5,370 W',
    powerValue: 5370,
    efficiency: '15.0 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s21-plus-hydro-358t.svg' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer S21+ Hydro 358 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 358 TH/s with a power consumption of 5,370 W, offering an efficiency of 15.0 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21+ Hydro (358T)',
      release: 'Not specified',
      noiseLevel: 'Not specified (liquid-cooled)',
      fans: 'Liquid-cooled',
      interface: 'Ethernet',
      temperature: 'Coolant inlet 20 - 50 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '339 x 173 x 207',
    weightKg: 14.5,
    psuIncluded: null,
    sourceUrl: 'https://www.unistarminer.com/products/bitmain-antminer-bitcoin-miner-s21-hyd-358t-395t-unistar',
  },
  {
    slug: 'bitmain-antminer-t21-190t',
    title: 'Bitmain Antminer T21 190 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '190 TH/s',
    hashrateValue: 190,
    hashrateHz: 190e12,
    power: '3,610 W',
    powerValue: 3610,
    efficiency: '19.0 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-t21-190t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer T21 190 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 190 TH/s with a power consumption of 3,610 W, offering an efficiency of 19.0 J/TH. LOW CONFIDENCE: Bitmain\'s own support page 403\'d our fetch attempts — dimensions/weight below come from reseller listings that disagree with each other (dimensions also reported as 400x212x290mm; weight elsewhere reported 14.1-18kg); please verify before publishing.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer T21 (190T)',
      release: 'Not specified',
      noiseLevel: '75db',
      fans: '2',
      interface: 'Ethernet',
      temperature: '0 - 45 °C',
      humidity: '10 - 90 %',
    },
    dimensionsMm: '400 x 195 x 290',
    weightKg: 16.4,
    psuIncluded: null,
    sourceUrl: 'https://www.for-mining.fr/en/product-page/bitmain-t21-190t-triphas%C3%A9',
  },
  {
    slug: 'bitmain-antminer-z15-pro-840k',
    title: 'Bitmain Antminer Z15 Pro 840 KSol/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '840 KSol/s',
    hashrateValue: 840,
    hashrateHz: 840e3,
    power: '2,780 W',
    powerValue: 2780,
    efficiency: '3.3 J/KSol',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-z15-pro-840k.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Equihash',
    mineableCoins: [{ name: 'Zcash', ticker: 'ZEC' }],
    description:
      'The Bitmain Antminer Z15 Pro 840 KSol/s is an ASIC miner designed for the Equihash algorithm. It delivers a hashrate of 840 KSol/s with a power consumption of 2,780 W, offering an efficiency of 3.3 J/KSol. Zcash/Equihash is measured in Sol/s rather than H/s — unit inferred, not from an explicit source rule.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer Z15 Pro 840K',
      release: 'Not specified',
      noiseLevel: '75db',
      fans: '2',
      interface: 'Ethernet',
      temperature: '0 - 40 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '360 x 200 x 290',
    weightKg: 16.9,
    psuIncluded: null,
    sourceUrl: 'https://xonmining.com/product/antminer-z15-pro/',
  },
  {
    slug: 'bitmain-antminer-s21-plus-hyd-395th',
    title: 'Bitmain Antminer S21+ Hyd 395 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '395 TH/s',
    hashrateValue: 395,
    hashrateHz: 395e12,
    power: '5,950 W',
    powerValue: 5950,
    powerWattsPublished: 5925,
    efficiency: '15.1 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s21-plus-hyd-395th.svg' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer S21+ Hyd 395 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 395 TH/s with a power consumption of 5,950 W, offering an efficiency of 15.1 J/TH. FLAG: reseller listings publish 5925W for this exact bin (vs 5,950W in our source list) — close enough to likely be rounding, noted for verification.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21+ Hyd (395Th)',
      release: 'Not specified',
      noiseLevel: 'Not specified (liquid-cooled)',
      fans: 'Liquid-cooled',
      interface: 'Ethernet',
      temperature: 'Coolant inlet 20 - 50 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '339 x 173 x 207',
    weightKg: 14.5,
    psuIncluded: null,
    sourceUrl: 'https://viperatech.com/product/bitmain-antminer-s21-hydro-395th-s-5925w',
  },
  {
    slug: 'iceriver-al3-15t',
    title: 'IceRiver AL3 15 TH/s',
    tag: 'ICERIVER',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '15 TH/s',
    hashrateValue: 15,
    hashrateHz: 15e12,
    power: '3,500 W',
    powerValue: 3500,
    efficiency: '233.3 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/iceriver-al3-15t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'IceRiver',
    algorithm: 'Blake3',
    mineableCoins: [{ name: 'Alephium', ticker: 'ALPH' }],
    description:
      'The IceRiver AL3 15 TH/s is an ASIC miner designed for the Blake3 algorithm. It delivers a hashrate of 15 TH/s with a power consumption of 3,500 W, offering an efficiency of 233.3 J/TH.',
    specs: {
      manufacturer: 'IceRiver',
      model: 'AL3 15T',
      release: 'Sep 2024',
      noiseLevel: '75db',
      fans: '2',
      interface: 'Ethernet',
      temperature: '5 - 40 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '370 x 195 x 290',
    weightKg: 16,
    psuIncluded: null,
    sourceUrl: 'https://bt-miners.com/products/iceriver-al3-alephium-miner-15th-s-bt-miners/',
  },
  {
    slug: 'iceriver-ks3l-5t',
    title: 'IceRiver KS3L 5 TH/s',
    tag: 'ICERIVER',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '5 TH/s',
    hashrateValue: 5,
    hashrateHz: 5e12,
    power: '3,180 W',
    powerValue: 3180,
    efficiency: '636.0 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/iceriver-ks3l-5t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'IceRiver',
    algorithm: 'KHeavyHash',
    mineableCoins: [{ name: 'Kaspa', ticker: 'KAS' }],
    description:
      'The IceRiver KS3L 5 TH/s is an ASIC miner designed for the KHeavyHash algorithm. It delivers a hashrate of 5 TH/s with a power consumption of 3,180 W, offering an efficiency of 636.0 J/TH. LOW CONFIDENCE: no distinct dimensions/weight found for KS3L specifically — not populated rather than guessed from the KS3M/KS5M family.',
    specs: {
      manufacturer: 'IceRiver',
      model: 'KS3L (5T)',
      release: 'Not specified',
      noiseLevel: 'Not specified',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '5 - 40 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: null,
    weightKg: null,
    psuIncluded: null,
    sourceUrl: 'https://bt-miners.com/products/iceriver-ks5l-kaspa-miner-12th-s-bt-miners/',
  },
  {
    slug: 'iceriver-ks3m-6t',
    title: 'IceRiver KS3M 6 TH/s',
    tag: 'ICERIVER',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '6 TH/s',
    hashrateValue: 6,
    hashrateHz: 6e12,
    power: '3,400 W',
    powerValue: 3400,
    efficiency: '566.7 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/iceriver-ks3m-6t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'IceRiver',
    algorithm: 'KHeavyHash',
    mineableCoins: [{ name: 'Kaspa', ticker: 'KAS' }],
    description:
      'The IceRiver KS3M 6 TH/s is an ASIC miner designed for the KHeavyHash algorithm. It delivers a hashrate of 6 TH/s with a power consumption of 3,400 W, offering an efficiency of 566.7 J/TH. Hashrate anchored on the trailing "(6T)" — a naive parse of "KS3M" would have misread this as a 3M-hashrate product.',
    specs: {
      manufacturer: 'IceRiver',
      model: 'KS3M (6T)',
      release: 'Not specified',
      noiseLevel: '75db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '5 - 40 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '370 x 195 x 290',
    weightKg: 14.4,
    psuIncluded: null,
    sourceUrl: 'https://www.iceriver.io/product/iceriver-ks3m/',
  },
  {
    slug: 'iceriver-ks5m-15t',
    title: 'IceRiver KS5M 15 TH/s',
    tag: 'ICERIVER',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '15 TH/s',
    hashrateValue: 15,
    hashrateHz: 15e12,
    power: '3,400 W',
    powerValue: 3400,
    efficiency: '226.7 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/iceriver-ks5m-15t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'IceRiver',
    algorithm: 'KHeavyHash',
    mineableCoins: [{ name: 'Kaspa', ticker: 'KAS' }],
    description:
      'The IceRiver KS5M 15 TH/s is an ASIC miner designed for the KHeavyHash algorithm. It delivers a hashrate of 15 TH/s with a power consumption of 3,400 W, offering an efficiency of 226.7 J/TH. Hashrate anchored on the trailing "(15T)" — a naive parse of "KS5M" would have misread this as a 5M-hashrate product. Dimensions/weight assumed shared with the KS3M chassis — not independently confirmed.',
    specs: {
      manufacturer: 'IceRiver',
      model: 'KS5M (15T)',
      release: 'Not specified',
      noiseLevel: 'Not specified',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '5 - 40 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '370 x 195 x 290',
    weightKg: 14.4,
    psuIncluded: null,
    sourceUrl: 'https://bt-miners.com/products/iceriver-ks5m-kaspa-miner-15th-s-bt-miners/',
  },
  {
    slug: 'bitmain-antminer-s21-plus-235t',
    title: 'Bitmain Antminer S21+ 235 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '235 TH/s',
    hashrateValue: 235,
    hashrateHz: 235e12,
    power: '3,870 W',
    powerValue: 3870,
    powerWattsPublished: 3878,
    efficiency: '16.5 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s21-plus-235t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'The Bitmain Antminer S21+ 235 TH/s is a high-performance ASIC miner designed for the SHA-256 algorithm. It delivers a hashrate of 235 TH/s with a power consumption of 3,870 W, offering an efficiency of 16.5 J/TH. FLAG: reseller listings publish 3878W for this exact bin (vs 3,870W in our source list) — likely rounding, noted for verification.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21+ (235T)',
      release: 'Not specified',
      noiseLevel: '75db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '-5 - 40 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '400 x 195 x 290',
    weightKg: null,
    psuIncluded: null,
    sourceUrl: 'https://www.cryptominerbros.com/product/bitmain-antminer-s21-plus-bitcoin-miner/',
  },
  {
    slug: 'iceriver-ae2-720m',
    title: 'IceRiver AE2 720 M/s',
    tag: 'ICERIVER',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '720 M/s',
    hashrateValue: 720,
    hashrateHz: 720e6,
    power: '1,300 W',
    powerValue: 1300,
    efficiency: '1.8 J/M',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/iceriver-ae2-720m.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'IceRiver',
    algorithm: 'zkSNARK',
    mineableCoins: [{ name: 'Aleo', ticker: 'ALEO' }],
    description:
      'The IceRiver AE2 720 M/s is an ASIC miner designed for the zkSNARK algorithm. It delivers a hashrate of 720 M/s with a power consumption of 1,300 W, offering an efficiency of 1.8 J/M.',
    specs: {
      manufacturer: 'IceRiver',
      model: 'AE2 720m',
      release: 'Not specified',
      noiseLevel: '45 - 60db (sources disagree)',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '0 - 40 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '205 x 110 x 202',
    weightKg: 4.02,
    psuIncluded: null,
    sourceUrl: 'https://asicmarketplace.com/product/iceriver-ae2-aleo-miner/',
  },
  {
    slug: 'microbt-whatsminer-m60',
    title: 'MicroBT Whatsminer M60',
    tag: 'MICROBT',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: 'Unverified',
    hashrateValue: null,
    hashrateHz: null,
    power: '3,440 W',
    powerValue: 3440,
    efficiency: 'Unverified',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/microbt-whatsminer-m60.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Needs review: the source list gave "Whatsminer M60" with no hashrate figure in the name, unlike every other row. MicroBT ships several real M60-series bins (roughly 156-172 TH/s at ~3.42kW per public listings), but which one this row refers to was not stated, so hashrate/efficiency are left unset rather than guessed.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M60',
      release: 'Not specified',
      noiseLevel: '72db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: '-5 - 35 °C',
      humidity: 'Not specified',
    },
    dimensionsMm: '430 x 155 x 226',
    weightKg: 13.5,
    psuIncluded: true,
    sourceUrl: 'https://hashrateindex.com/blog/whatsminer-m60-and-m60s-profitability-guide/',
    needsReview: true,
  },
  {
    slug: 'pinecone-matches-inibox-850m',
    title: 'Pinecone Matches INIBOX 850 M/s',
    tag: 'PINECONE',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '850 M/s',
    hashrateValue: 850,
    hashrateHz: 850e6,
    power: '500 W',
    powerValue: 500,
    efficiency: '0.6 J/M',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/pinecone-matches-inibox-850m.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Pinecone',
    algorithm: 'VersaHash',
    mineableCoins: [{ name: 'InitVerse', ticker: 'INI' }],
    description:
      'The Pinecone Matches INIBOX 850 M/s is an ASIC miner designed for the VersaHash algorithm. It delivers a hashrate of 850 M/s with a power consumption of 500 W, offering an efficiency of 0.6 J/M.',
    specs: {
      manufacturer: 'Pinecone',
      model: 'Matches INIBOX (850M)',
      release: 'Not specified',
      noiseLevel: '60db',
      fans: 'Not specified',
      interface: 'Ethernet',
      temperature: 'Not specified',
      humidity: 'Not specified',
    },
    dimensionsMm: '196 x 165 x 125',
    weightKg: 3.05,
    psuIncluded: true,
    sourceUrl: 'https://viperatech.com/product/pinecone-matches-inibox-850mh-s-initverse-miner',
  },
  {
    slug: 'pinecone-matches-inibox-pro-2-4g',
    title: 'Pinecone Matches INIBOX Pro 2.4 GH/s',
    tag: 'PINECONE',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '2.4 GH/s',
    hashrateValue: 2.4,
    hashrateHz: 2.4e9,
    power: '1,280 W',
    powerValue: 1280,
    efficiency: '0.5 J/M',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/pinecone-matches-inibox-pro-2-4g.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Pinecone',
    algorithm: 'VersaHash',
    mineableCoins: [{ name: 'InitVerse', ticker: 'INI' }],
    description:
      'The Pinecone Matches INIBOX Pro 2.4 GH/s is an ASIC miner designed for the VersaHash algorithm. It delivers a hashrate of 2.4 GH/s with a power consumption of 1,280 W, offering an efficiency of 0.5 J/M (converted from 2.4G to 2400M for a unit-consistent efficiency figure).',
    specs: {
      manufacturer: 'Pinecone',
      model: 'Matches INIBOX Pro (2.4G)',
      release: 'Not specified',
      noiseLevel: '70db',
      fans: '2',
      interface: 'Ethernet',
      temperature: '5 - 40 °C',
      humidity: '5 - 95 %',
    },
    dimensionsMm: '270 x 184 x 291',
    weightKg: 10.7,
    psuIncluded: true,
    sourceUrl: 'https://oneminers.com/products/pinecone-inibox-pro-2-4-gh-s',
  },
  {
    slug: 'bitmain-antminer-ks5-20t',
    title: 'Bitmain Antminer KS5 20 TH/s',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '20 TH/s',
    hashrateValue: 20,
    hashrateHz: 20e12,
    power: '3,000 W',
    powerValue: 3000,
    efficiency: '150.0 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-ks5-20t.svg' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'KHeavyHash',
    mineableCoins: [{ name: 'Kaspa', ticker: 'KAS' }],
    description:
      'The Bitmain Antminer KS5 20 TH/s is an ASIC miner designed for the KHeavyHash algorithm. It delivers a hashrate of 20 TH/s with a power consumption of 3,000 W, offering an efficiency of 150.0 J/TH.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer KS5 (20T)',
      release: 'Mar 2024',
      noiseLevel: '76db',
      fans: '4',
      interface: 'Ethernet',
      temperature: '0 - 40 °C',
      humidity: '10 - 90 %',
    },
    dimensionsMm: '430 x 195 x 290',
    weightKg: 15.8,
    psuIncluded: null,
    sourceUrl: 'https://miningstore.com/cryptocurrency-mining-machines/bitmain-antminer-ks5-20th-kaspa-miner/',
  },
]

export const products: Product[] = baseProducts.filter((product) => !product.needsReview)

export function getProductBySlug(slug: string): Product | undefined {
  return baseProducts.find((product) => product.slug === slug)
}
