export type Category = 'Air Cooling Miners' | 'Hydro Cooling Miners' | 'Immersion Miners'
export type Brand = 'MicroBT' | 'Bitmain' | 'Bitdeer' | 'Canaan' | 'Elphapex'
export type Cooling = 'air' | 'hydro'

export interface Product {
  slug: string
  title: string
  tag: string
  price: string
  priceUsd: number | null
  status?: 'In Stock' | 'No Stock'
  hashrate: string
  hashrateValue: number | null
  // Hashrate normalized to hashes-per-second, used only for cross-unit sort
  // comparisons (TH/s, GH/s, MH/s, KH/s aren't directly comparable as raw numbers).
  hashrateHz: number | null
  power: string
  powerValue: number
  efficiency: string
  media: { type: 'image' | 'video'; src: string }
  category: Category
  cooling: Cooling
  brand: Brand
  algorithm: string
  mineableCoins: { name: string; ticker: string }[]
  description: string
  specs: {
    manufacturer: string
    model: string
    release: string
    noiseLevel: string
    fans: string
    interface: string
    inputVoltage: string
    temperature: string
    humidity: string
  }
  dimensionsMm?: string | null
  weightKg?: number | null
  psuIncluded?: boolean | null
  sourceUrl?: string | null
  // Internal QA note from the developer upload sheet — not shown publicly.
  developerNote?: string
  seoTitle?: string
  metaDescription?: string
  // Set for rows the developer upload sheet explicitly marked "Do not upload"
  // (unresolved model/spec conflicts) — excluded from every public listing.
  needsReview?: boolean
}

export const baseProducts: Product[] = [
  // --- BitMars "Selected Products" catalogue (Qubite_Website_Products_Full.md, sheet
  // "Website products"). Row order matches that sheet; each product's developerNote
  // records its exact source row. Prices are BitMars' website (customer-facing) prices,
  // not raw EXW wholesale cost.
  {
    slug: 'antminer-s23e-hydro-2u-mixed-865th',
    title: 'Antminer S23e Hydro 2U (Mixed) 865 TH/s',
    tag: 'BITMAIN',
    price: '$9,996',
    priceUsd: 9996,
    hashrate: '865 TH/s',
    hashrateValue: 865,
    hashrateHz: 865000000000000,
    power: '8650 W',
    powerValue: 8650,
    efficiency: '10 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s23e-hydro-2u-mixed-865th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S23e Hydro 2U (Mixed) 865 TH/s is a SHA-256 ASIC miner rated at 865 TH/s with listed power of 8650 W. Currently listed as preorder stock, with estimated delivery: Nov-Jan delivery. This is a mixed-hashrate allocation: the exact hashrate delivered is subject to factory allocation at time of shipment. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S23e Hydro 2U (Mixed) 865 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S23e Hydro 2U (Mixed) 865 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S23e Hydro 2U (Mixed) 865 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 8. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s23-xp-hydro-mixed-600th',
    title: 'Antminer S23 XP Hydro (Mixed) 600 TH/s',
    tag: 'BITMAIN',
    price: '$15,880',
    priceUsd: 15880,
    hashrate: '600 TH/s',
    hashrateValue: 600,
    hashrateHz: 600000000000000,
    power: '5340 W',
    powerValue: 5340,
    efficiency: '8.9 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s23-xp-hydro-mixed-600th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S23 XP Hydro (Mixed) 600 TH/s is a SHA-256 ASIC miner rated at 600 TH/s with listed power of 5340 W. Currently listed as preorder stock, with estimated delivery: Nov delivery. This is a mixed-hashrate allocation: the exact hashrate delivered is subject to factory allocation at time of shipment. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S23 XP Hydro (Mixed) 600 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S23 XP Hydro (Mixed) 600 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S23 XP Hydro (Mixed) 600 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 9. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s23-hydro-563th',
    title: 'Antminer S23 Hydro 563 TH/s',
    tag: 'BITMAIN',
    price: '$13,499',
    priceUsd: 13499,
    hashrate: '563 TH/s',
    hashrateValue: 563,
    hashrateHz: 563000000000000,
    power: '5349 W',
    powerValue: 5348.5,
    efficiency: '9.5 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s23-hydro-563th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S23 Hydro 563 TH/s is a SHA-256 ASIC miner rated at 563 TH/s with listed power of 5349 W. Estimated availability: HK Stock. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S23 Hydro 563 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S23 Hydro 563 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S23 Hydro 563 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 10. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s21j-xp-hydro-495th',
    title: 'Antminer S21j XP Hydro 495 TH/s',
    tag: 'BITMAIN',
    price: '$6,643',
    priceUsd: 6643,
    hashrate: '495 TH/s',
    hashrateValue: 495,
    hashrateHz: 495000000000000,
    power: '5940 W',
    powerValue: 5940,
    efficiency: '12 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s21j-xp-hydro-495th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S21j XP Hydro 495 TH/s is a SHA-256 ASIC miner rated at 495 TH/s with listed power of 5940 W. Estimated availability: HK Stock. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21j XP Hydro 495 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S21j XP Hydro 495 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S21j XP Hydro 495 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 11. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s21-hydro-395th',
    title: 'Antminer S21+ Hydro 395 TH/s',
    tag: 'BITMAIN',
    price: '$3,528',
    priceUsd: 3528,
    hashrate: '395 TH/s',
    hashrateValue: 395,
    hashrateHz: 395000000000000,
    power: '5925 W',
    powerValue: 5925,
    efficiency: '15 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s21-hydro-395th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S21+ Hydro 395 TH/s is a SHA-256 ASIC miner rated at 395 TH/s with listed power of 5925 W. Estimated availability: 4 days HK. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21+ Hydro 395 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S21+ Hydro 395 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S21+ Hydro 395 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 12. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s21-hydro-358th',
    title: 'Antminer S21+ Hydro 358 TH/s',
    tag: 'BITMAIN',
    price: '$3,220',
    priceUsd: 3220,
    hashrate: '358 TH/s',
    hashrateValue: 358,
    hashrateHz: 358000000000000,
    power: '5370 W',
    powerValue: 5370,
    efficiency: '15 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s21-hydro-358th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S21+ Hydro 358 TH/s is a SHA-256 ASIC miner rated at 358 TH/s with listed power of 5370 W. Estimated availability: HK Stock. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21+ Hydro 358 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S21+ Hydro 358 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S21+ Hydro 358 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 13. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s21e-hydro-310th',
    title: 'Antminer S21e Hydro 310 TH/s',
    tag: 'BITMAIN',
    price: '$2,333',
    priceUsd: 2333,
    hashrate: '310 TH/s',
    hashrateValue: 310,
    hashrateHz: 310000000000000,
    power: '5270 W',
    powerValue: 5270,
    efficiency: '17 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s21e-hydro-310th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S21e Hydro 310 TH/s is a SHA-256 ASIC miner rated at 310 TH/s with listed power of 5270 W. Estimated availability: HK Stock. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21e Hydro 310 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S21e Hydro 310 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S21e Hydro 310 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 14. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s21e-hydro-332th',
    title: 'Antminer S21e Hydro 332 TH/s',
    tag: 'BITMAIN',
    price: '$2,494',
    priceUsd: 2494,
    hashrate: '332 TH/s',
    hashrateValue: 332,
    hashrateHz: 332000000000000,
    power: '5644 W',
    powerValue: 5644,
    efficiency: '17 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s21e-hydro-332th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S21e Hydro 332 TH/s is a SHA-256 ASIC miner rated at 332 TH/s with listed power of 5644 W. Estimated availability: HK Stock. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21e Hydro 332 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S21e Hydro 332 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S21e Hydro 332 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 15. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s21e-hydro-288th',
    title: 'Antminer S21e Hydro 288 TH/s',
    tag: 'BITMAIN',
    price: '$2,181',
    priceUsd: 2181,
    hashrate: '288 TH/s',
    hashrateValue: 288,
    hashrateHz: 288000000000000,
    power: '4896 W',
    powerValue: 4896,
    efficiency: '17 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s21e-hydro-288th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S21e Hydro 288 TH/s is a SHA-256 ASIC miner rated at 288 TH/s with listed power of 4896 W. Estimated availability: HK Stock. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21e Hydro 288 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S21e Hydro 288 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S21e Hydro 288 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 16. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s19-xp-hydro-293th',
    title: 'Antminer S19 XP+ Hydro 293 TH/s',
    tag: 'BITMAIN',
    price: '$2,084',
    priceUsd: 2084,
    hashrate: '293 TH/s',
    hashrateValue: 293,
    hashrateHz: 293000000000000,
    power: '5567 W',
    powerValue: 5567,
    efficiency: '19 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s19-xp-hydro-293th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S19 XP+ Hydro 293 TH/s is a SHA-256 ASIC miner rated at 293 TH/s with listed power of 5567 W. Estimated availability: 6 days HK. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19 XP+ Hydro 293 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S19 XP+ Hydro 293 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S19 XP+ Hydro 293 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 17. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s19-xp-hydro-279th',
    title: 'Antminer S19 XP+ Hydro 279 TH/s',
    tag: 'BITMAIN',
    price: '$2,004',
    priceUsd: 2004,
    hashrate: '279 TH/s',
    hashrateValue: 279,
    hashrateHz: 279000000000000,
    power: '5301 W',
    powerValue: 5301,
    efficiency: '19 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s19-xp-hydro-279th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S19 XP+ Hydro 279 TH/s is a SHA-256 ASIC miner rated at 279 TH/s with listed power of 5301 W. Estimated availability: 6 days HK. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19 XP+ Hydro 279 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S19 XP+ Hydro 279 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S19 XP+ Hydro 279 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 18. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s19-xp-hydro-252th',
    title: 'Antminer S19 XP+ Hydro 252 TH/s',
    tag: 'BITMAIN',
    price: '$1,882',
    priceUsd: 1882,
    hashrate: '252 TH/s',
    hashrateValue: 252,
    hashrateHz: 252000000000000,
    power: '4788 W',
    powerValue: 4788,
    efficiency: '19 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s19-xp-hydro-252th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S19 XP+ Hydro 252 TH/s is a SHA-256 ASIC miner rated at 252 TH/s with listed power of 4788 W. Estimated availability: 6 days HK. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19 XP+ Hydro 252 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S19 XP+ Hydro 252 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S19 XP+ Hydro 252 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 19. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s19-xp-hydro-257th',
    title: 'Antminer S19 XP Hydro 257 TH/s',
    tag: 'BITMAIN',
    price: '$1,694',
    priceUsd: 1694,
    hashrate: '257 TH/s',
    hashrateValue: 257,
    hashrateHz: 257000000000000,
    power: '5346 W',
    powerValue: 5345.6,
    efficiency: '20.8 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s19-xp-hydro-257th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S19 XP Hydro 257 TH/s is a SHA-256 ASIC miner rated at 257 TH/s with listed power of 5346 W. Estimated availability: HK Stock. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19 XP Hydro 257 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S19 XP Hydro 257 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S19 XP Hydro 257 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 20. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s21-exp-hydro-430th',
    title: 'Antminer S21 EXP Hydro 430 TH/s',
    tag: 'BITMAIN',
    price: '$4,526',
    priceUsd: 4526,
    hashrate: '430 TH/s',
    hashrateValue: 430,
    hashrateHz: 430000000000000,
    power: '5590 W',
    powerValue: 5590,
    efficiency: '13 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s21-exp-hydro-430th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S21 EXP Hydro 430 TH/s is a SHA-256 ASIC miner rated at 430 TH/s with listed power of 5590 W. Estimated availability: HK Stock. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21 EXP Hydro 430 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S21 EXP Hydro 430 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S21 EXP Hydro 430 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 21. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-u3s21exp-hydro-860th',
    title: 'Antminer U3S21EXP Hydro 860 TH/s',
    tag: 'BITMAIN',
    price: '$8,396',
    priceUsd: 8396,
    hashrate: '860 TH/s',
    hashrateValue: 860,
    hashrateHz: 860000000000000,
    power: '11180 W',
    powerValue: 11180,
    efficiency: '13 J/TH',
    media: { type: 'image', src: '/images/products/antminer-u3s21exp-hydro-860th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer U3S21EXP Hydro 860 TH/s is a SHA-256 ASIC miner rated at 860 TH/s with listed power of 11180 W. Estimated availability: HK Stock. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer U3S21EXP Hydro 860 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer U3S21EXP Hydro 860 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer U3S21EXP Hydro 860 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 22. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s19-exp-hydro-251th',
    title: 'Antminer S19 EXP Hydro 251 TH/s',
    tag: 'BITMAIN',
    price: '$1,728',
    priceUsd: 1728,
    hashrate: '251 TH/s',
    hashrateValue: 251,
    hashrateHz: 251000000000000,
    power: '5522 W',
    powerValue: 5522,
    efficiency: '22 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s19-exp-hydro-251th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S19 EXP Hydro 251 TH/s is a SHA-256 ASIC miner rated at 251 TH/s with listed power of 5522 W. Estimated availability: 15 days HK. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19 EXP Hydro 251 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S19 EXP Hydro 251 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S19 EXP Hydro 251 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 23. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s21-xp-270th',
    title: 'Antminer S21 XP 270 TH/s',
    tag: 'BITMAIN',
    price: '$4,078',
    priceUsd: 4078,
    hashrate: '270 TH/s',
    hashrateValue: 270,
    hashrateHz: 270000000000000,
    power: '3645 W',
    powerValue: 3645,
    efficiency: '13.5 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s21-xp-270th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S21 XP 270 TH/s is a SHA-256 ASIC miner rated at 270 TH/s with listed power of 3645 W. Estimated availability: HK Stock. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21 XP 270 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S21 XP 270 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S21 XP 270 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 24. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s21-pro-245th',
    title: 'Antminer S21 Pro+ 245 TH/s',
    tag: 'BITMAIN',
    price: '$2,960',
    priceUsd: 2960,
    hashrate: '245 TH/s',
    hashrateValue: 245,
    hashrateHz: 245000000000000,
    power: '3675 W',
    powerValue: 3675,
    efficiency: '15 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s21-pro-245th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S21 Pro+ 245 TH/s is a SHA-256 ASIC miner rated at 245 TH/s with listed power of 3675 W. Estimated availability: HK Stock. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21 Pro+ 245 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S21 Pro+ 245 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S21 Pro+ 245 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 25. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-s21-pro-234th',
    title: 'Antminer S21 Pro+ 234 TH/s',
    tag: 'BITMAIN',
    price: '$2,661',
    priceUsd: 2661,
    hashrate: '234 TH/s',
    hashrateValue: 234,
    hashrateHz: 234000000000000,
    power: '3510 W',
    powerValue: 3510,
    efficiency: '15 J/TH',
    media: { type: 'image', src: '/images/products/antminer-s21-pro-234th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Antminer S21 Pro+ 234 TH/s is a SHA-256 ASIC miner rated at 234 TH/s with listed power of 3510 W. Estimated availability: HK Stock. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21 Pro+ 234 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer S21 Pro+ 234 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer S21 Pro+ 234 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 26. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-l9-90-day-warranty-15gh',
    title: 'Antminer L9 (90-day warranty) 15 GH/s',
    tag: 'BITMAIN',
    price: '$3,450',
    priceUsd: 3450,
    hashrate: '15 GH/s',
    hashrateValue: 15,
    hashrateHz: 15000000000,
    power: '3150 W',
    powerValue: 3150,
    efficiency: '210 J/GH',
    media: { type: 'image', src: '/images/products/antminer-l9-90-day-warranty-15gh.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [{ name: 'Dogecoin', ticker: 'DOGE' }, { name: 'Litecoin', ticker: 'LTC' }],
    description: 'Antminer L9 (90-day warranty) 15 GH/s is a Scrypt ASIC miner rated at 15 GH/s with listed power of 3150 W. Estimated availability: HK Stock. Covered by a 90-day warranty. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L9 (90-day warranty) 15 GH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer L9 (90-day warranty) 15 GH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer L9 (90-day warranty) 15 GH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 37. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-l9-90-day-warranty-16gh',
    title: 'Antminer L9 (90-day warranty) 16 GH/s',
    tag: 'BITMAIN',
    price: '$3,650',
    priceUsd: 3650,
    hashrate: '16 GH/s',
    hashrateValue: 16,
    hashrateHz: 16000000000,
    power: '3360 W',
    powerValue: 3360,
    efficiency: '210 J/GH',
    media: { type: 'image', src: '/images/products/antminer-l9-90-day-warranty-16gh.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [{ name: 'Dogecoin', ticker: 'DOGE' }, { name: 'Litecoin', ticker: 'LTC' }],
    description: 'Antminer L9 (90-day warranty) 16 GH/s is a Scrypt ASIC miner rated at 16 GH/s with listed power of 3360 W. Estimated availability: HK Stock. Covered by a 90-day warranty. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L9 (90-day warranty) 16 GH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer L9 (90-day warranty) 16 GH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer L9 (90-day warranty) 16 GH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 38. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-l7-170-day-warranty-9050mh',
    title: 'Antminer L7 (170-day warranty) 9050 MH/s',
    tag: 'BITMAIN',
    price: '$1,650',
    priceUsd: 1650,
    hashrate: '9050 MH/s',
    hashrateValue: 9050,
    hashrateHz: 9050000000,
    power: '3425 W',
    powerValue: 3425,
    efficiency: '0.378 J/MH',
    media: { type: 'image', src: '/images/products/antminer-l7-170-day-warranty-9050mh.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [{ name: 'Dogecoin', ticker: 'DOGE' }, { name: 'Litecoin', ticker: 'LTC' }],
    description: 'Antminer L7 (170-day warranty) 9050 MH/s is a Scrypt ASIC miner rated at 9050 MH/s with listed power of 3425 W. Estimated availability: HK Stock. Covered by a 170-day warranty. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L7 (170-day warranty) 9050 MH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer L7 (170-day warranty) 9050 MH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer L7 (170-day warranty) 9050 MH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 39. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-l7-150-day-warranty-8800mh',
    title: 'Antminer L7 (150-day warranty) 8800 MH/s',
    tag: 'BITMAIN',
    price: '$1,630',
    priceUsd: 1630,
    hashrate: '8800 MH/s',
    hashrateValue: 8800,
    hashrateHz: 8800000000,
    power: '3330 W',
    powerValue: 3330,
    efficiency: '0.378 J/MH',
    media: { type: 'image', src: '/images/products/antminer-l7-150-day-warranty-8800mh.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [{ name: 'Dogecoin', ticker: 'DOGE' }, { name: 'Litecoin', ticker: 'LTC' }],
    description: 'Antminer L7 (150-day warranty) 8800 MH/s is a Scrypt ASIC miner rated at 8800 MH/s with listed power of 3330 W. Estimated availability: HK Stock. Covered by a 150-day warranty. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L7 (150-day warranty) 8800 MH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer L7 (150-day warranty) 8800 MH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer L7 (150-day warranty) 8800 MH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 40. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'antminer-u2l9-27gh',
    title: 'Antminer U2L9 27 GH/s',
    tag: 'BITMAIN',
    price: '$6,670',
    priceUsd: 6670,
    hashrate: '27 GH/s',
    hashrateValue: 27,
    hashrateHz: 27000000000,
    power: '5670 W',
    powerValue: 5670,
    efficiency: '210 J/GH',
    media: { type: 'image', src: '/images/products/antminer-u2l9-27gh.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [{ name: 'Dogecoin', ticker: 'DOGE' }, { name: 'Litecoin', ticker: 'LTC' }],
    description: 'Antminer U2L9 27 GH/s is a Scrypt ASIC miner rated at 27 GH/s with listed power of 5670 W. Estimated availability: 7 days HK. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer U2L9 27 GH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Antminer U2L9 27 GH/s ASIC Miner | Qubite International',
    metaDescription: 'View Antminer U2L9 27 GH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 41. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m63-363-382th',
    title: 'Whatsminer M63 363 - 382 TH/s',
    tag: 'MICROBT',
    price: '$2,742',
    priceUsd: 2742,
    hashrate: '363 - 382 TH/s',
    hashrateValue: 382,
    hashrateHz: 382000000000000,
    power: '6897 - 7258 W',
    powerValue: 7258,
    efficiency: '19 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m63-363-382th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M63 363 - 382 TH/s is a SHA-256 ASIC miner rated at 363 - 382 TH/s with listed power of 6897 - 7258 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 363 - 382 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $2,834 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M63 363 - 382 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M63 363 - 382 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M63 363 - 382 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 48. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m63-334-374th',
    title: 'Whatsminer M63 334 - 374 TH/s',
    tag: 'MICROBT',
    price: '$2,503',
    priceUsd: 2503,
    hashrate: '334 - 374 TH/s',
    hashrateValue: 374,
    hashrateHz: 374000000000000,
    power: '6647 - 7443 W',
    powerValue: 7442.6,
    efficiency: '19.9 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m63-334-374th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M63 334 - 374 TH/s is a SHA-256 ASIC miner rated at 334 - 374 TH/s with listed power of 6647 - 7443 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 334 - 374 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $2,683 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M63 334 - 374 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M63 334 - 374 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M63 334 - 374 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 49. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m65s-392-404th',
    title: 'Whatsminer M65S 392 - 404 TH/s',
    tag: 'MICROBT',
    price: '$3,234',
    priceUsd: 3234,
    hashrate: '392 - 404 TH/s',
    hashrateValue: 404,
    hashrateHz: 404000000000000,
    power: '7252 - 7474 W',
    powerValue: 7474,
    efficiency: '18.5 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m65s-392-404th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M65S 392 - 404 TH/s is a SHA-256 ASIC miner rated at 392 - 404 TH/s with listed power of 7252 - 7474 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 392 - 404 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $3,303 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M65S 392 - 404 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M65S 392 - 404 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M65S 392 - 404 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 50. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m65s-398-416th',
    title: 'Whatsminer M65S+ 398 - 416 TH/s',
    tag: 'MICROBT',
    price: '$3,468',
    priceUsd: 3468,
    hashrate: '398 - 416 TH/s',
    hashrateValue: 416,
    hashrateHz: 416000000000000,
    power: '6766 - 7072 W',
    powerValue: 7072,
    efficiency: '17 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m65s-398-416th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M65S+ 398 - 416 TH/s is a SHA-256 ASIC miner rated at 398 - 416 TH/s with listed power of 6766 - 7072 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 398 - 416 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $3,579 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M65S+ 398 - 416 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M65S+ 398 - 416 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M65S+ 398 - 416 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 51. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m50s-144-146th',
    title: 'Whatsminer M50S+ 144 / 146 TH/s',
    tag: 'MICROBT',
    price: '$1,626',
    priceUsd: 1626,
    hashrate: '144 - 146 TH/s',
    hashrateValue: 146,
    hashrateHz: 146000000000000,
    power: '3312 - 3358 W',
    powerValue: 3358,
    efficiency: '23 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m50s-144-146th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M50S+ 144 / 146 TH/s is a SHA-256 ASIC miner rated at 144 - 146 TH/s with listed power of 3312 - 3358 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 144 - 146 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $1,635 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M50S+ 144 / 146 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M50S+ 144 / 146 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M50S+ 144 / 146 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 52. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m56s-210-224th',
    title: 'Whatsminer M56S+ 210 - 224 TH/s',
    tag: 'MICROBT',
    price: '$1,777',
    priceUsd: 1777,
    hashrate: '210 - 224 TH/s',
    hashrateValue: 224,
    hashrateHz: 224000000000000,
    power: '5040 - 5376 W',
    powerValue: 5376,
    efficiency: '24 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m56s-210-224th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M56S+ 210 - 224 TH/s is a SHA-256 ASIC miner rated at 210 - 224 TH/s with listed power of 5040 - 5376 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 210 - 224 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $1,829 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M56S+ 210 - 224 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M56S+ 210 - 224 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M56S+ 210 - 224 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 55. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m60s-200-206-210th',
    title: 'Whatsminer M60S+ 200/206/210 TH/s',
    tag: 'MICROBT',
    price: '$2,620',
    priceUsd: 2620,
    hashrate: '200 - 210 TH/s',
    hashrateValue: 210,
    hashrateHz: 210000000000000,
    power: '3400 - 3570 W',
    powerValue: 3570,
    efficiency: '17 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m60s-200-206-210th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M60S+ 200/206/210 TH/s is a SHA-256 ASIC miner rated at 200 - 210 TH/s with listed power of 3400 - 3570 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 200 - 210 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $2,701 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M60S+ 200/206/210 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M60S+ 200/206/210 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M60S+ 200/206/210 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 56. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m70s-254-260th',
    title: 'Whatsminer M70S 254 - 260 TH/s',
    tag: 'MICROBT',
    price: '$3,997',
    priceUsd: 3997,
    hashrate: '254 - 260 TH/s',
    hashrateValue: 260,
    hashrateHz: 260000000000000,
    power: '3429 - 3510 W',
    powerValue: 3510,
    efficiency: '13.5 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m70s-254-260th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M70S 254 - 260 TH/s is a SHA-256 ASIC miner rated at 254 - 260 TH/s with listed power of 3429 - 3510 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 254 - 260 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $4,068 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M70S 254 - 260 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M70S 254 - 260 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M70S 254 - 260 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 57. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m63s-370-402th',
    title: 'Whatsminer M63S 370 - 402 TH/s',
    tag: 'MICROBT',
    price: '$3,442',
    priceUsd: 3442,
    hashrate: '370 - 402 TH/s',
    hashrateValue: 402,
    hashrateHz: 402000000000000,
    power: '6845 - 7437 W',
    powerValue: 7437,
    efficiency: '18.5 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m63s-370-402th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M63S 370 - 402 TH/s is a SHA-256 ASIC miner rated at 370 - 402 TH/s with listed power of 6845 - 7437 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 370 - 402 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $3,653 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M63S 370 - 402 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M63S 370 - 402 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M63S 370 - 402 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 58. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m63s-396-400th',
    title: 'Whatsminer M63S+ 396 - 400 TH/s',
    tag: 'MICROBT',
    price: '$3,812',
    priceUsd: 3812,
    hashrate: '396 - 400 TH/s',
    hashrateValue: 400,
    hashrateHz: 400000000000000,
    power: '6732 - 6800 W',
    powerValue: 6800,
    efficiency: '17 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m63s-396-400th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M63S+ 396 - 400 TH/s is a SHA-256 ASIC miner rated at 396 - 400 TH/s with listed power of 6732 - 6800 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 396 - 400 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $3,840 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M63S+ 396 - 400 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M63S+ 396 - 400 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M63S+ 396 - 400 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 59. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m73-476-488th',
    title: 'Whatsminer M73 476 / 488 TH/s',
    tag: 'MICROBT',
    price: '$5,379',
    priceUsd: 5379,
    hashrate: '476 - 488 TH/s',
    hashrateValue: 488,
    hashrateHz: 488000000000000,
    power: '6902 - 7076 W',
    powerValue: 7076,
    efficiency: '14.5 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m73-476-488th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M73 476 / 488 TH/s is a SHA-256 ASIC miner rated at 476 - 488 TH/s with listed power of 6902 - 7076 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 476 - 488 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $5,490 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M73 476 / 488 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M73 476 / 488 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M73 476 / 488 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 60. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m73s-550-560th',
    title: 'Whatsminer M73S 550 - 560 TH/s',
    tag: 'MICROBT',
    price: '$7,160',
    priceUsd: 7160,
    hashrate: '550 - 560 TH/s',
    hashrateValue: 560,
    hashrateHz: 560000000000000,
    power: '7150 - 7280 W',
    powerValue: 7280,
    efficiency: '13 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m73s-550-560th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M73S 550 - 560 TH/s is a SHA-256 ASIC miner rated at 550 - 560 TH/s with listed power of 7150 - 7280 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 550 - 560 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $7,272 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M73S 550 - 560 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M73S 550 - 560 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M73S 550 - 560 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 61. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m73s-535-560th',
    title: 'Whatsminer M73S 535 - 560 TH/s',
    tag: 'MICROBT',
    price: '$6,778',
    priceUsd: 6778,
    hashrate: '535 - 560 TH/s',
    hashrateValue: 560,
    hashrateHz: 560000000000000,
    power: '7223 - 7560 W',
    powerValue: 7560,
    efficiency: '13.5 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m73s-535-560th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M73S 535 - 560 TH/s is a SHA-256 ASIC miner rated at 535 - 560 TH/s with listed power of 7223 - 7560 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 535 - 560 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $7,048 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M73S 535 - 560 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M73S 535 - 560 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M73S 535 - 560 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 62. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m74s-330-332th',
    title: 'Whatsminer M74S+ 330 / 332 TH/s',
    tag: 'MICROBT',
    price: '$5,604',
    priceUsd: 5604,
    hashrate: '330 - 332 TH/s',
    hashrateValue: 332,
    hashrateHz: 332000000000000,
    power: '3960 - 3984 W',
    powerValue: 3984,
    efficiency: '12 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m74s-330-332th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M74S+ 330 / 332 TH/s is a SHA-256 ASIC miner rated at 330 - 332 TH/s with listed power of 3960 - 3984 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 330 - 332 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $5,631 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M74S+ 330 / 332 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M74S+ 330 / 332 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M74S+ 330 / 332 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 63. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m74s-324th',
    title: 'Whatsminer M74S+ 324 TH/s',
    tag: 'MICROBT',
    price: '$5,342',
    priceUsd: 5342,
    hashrate: '324 TH/s',
    hashrateValue: 324,
    hashrateHz: 324000000000000,
    power: '4050 W',
    powerValue: 4050,
    efficiency: '12.5 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m74s-324th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M74S+ 324 TH/s is a SHA-256 ASIC miner rated at 324 TH/s with listed power of 4050 W. Estimated availability: SZ Stock. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M74S+ 324 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M74S+ 324 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M74S+ 324 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 64. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m7d-636-654th',
    title: 'Whatsminer M7D 636 - 654 TH/s',
    tag: 'MICROBT',
    price: '$6,724',
    priceUsd: 6724,
    hashrate: '636 - 654 TH/s',
    hashrateValue: 654,
    hashrateHz: 654000000000000,
    power: '8904 - 9156 W',
    powerValue: 9156,
    efficiency: '14 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m7d-636-654th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M7D 636 - 654 TH/s is a SHA-256 ASIC miner rated at 636 - 654 TH/s with listed power of 8904 - 9156 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 636 - 654 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $6,886 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M7D 636 - 654 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M7D 636 - 654 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M7D 636 - 654 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 65. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m7ds-672-678th',
    title: 'Whatsminer M7DS 672 / 678 TH/s',
    tag: 'MICROBT',
    price: '$7,854',
    priceUsd: 7854,
    hashrate: '672 - 678 TH/s',
    hashrateValue: 678,
    hashrateHz: 678000000000000,
    power: '9072 - 9153 W',
    powerValue: 9153,
    efficiency: '13.5 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m7ds-672-678th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M7DS 672 / 678 TH/s is a SHA-256 ASIC miner rated at 672 - 678 TH/s with listed power of 9072 - 9153 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 672 - 678 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $7,916 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M7DS 672 / 678 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M7DS 672 / 678 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M7DS 672 / 678 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 66. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m66-246-272-274th',
    title: 'Whatsminer M66 246/272/274 TH/s',
    tag: 'MICROBT',
    price: '$2,501',
    priceUsd: 2501,
    hashrate: '246 - 274 TH/s',
    hashrateValue: 274,
    hashrateHz: 274000000000000,
    power: '4895 - 5453 W',
    powerValue: 5452.6,
    efficiency: '19.9 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m66-246-272-274th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M66 246/272/274 TH/s is a SHA-256 ASIC miner rated at 246 - 274 TH/s with listed power of 4895 - 5453 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 246 - 274 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $2,671 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M66 246/272/274 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M66 246/272/274 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M66 246/272/274 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 67. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m66s-300-302th',
    title: 'Whatsminer M66S 300 / 302 TH/s',
    tag: 'MICROBT',
    price: '$3,040',
    priceUsd: 3040,
    hashrate: '300 - 302 TH/s',
    hashrateValue: 302,
    hashrateHz: 302000000000000,
    power: '5400 - 5436 W',
    powerValue: 5436,
    efficiency: '18 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m66s-300-302th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M66S 300 / 302 TH/s is a SHA-256 ASIC miner rated at 300 - 302 TH/s with listed power of 5400 - 5436 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 300 - 302 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $3,054 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M66S 300 / 302 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M66S 300 / 302 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M66S 300 / 302 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 68. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'whatsminer-m66s-280-322th',
    title: 'Whatsminer M66S+ 280 - 322 TH/s',
    tag: 'MICROBT',
    price: '$2,988',
    priceUsd: 2988,
    hashrate: '280 - 322 TH/s',
    hashrateValue: 322,
    hashrateHz: 322000000000000,
    power: '4760 - 5474 W',
    powerValue: 5474,
    efficiency: '17 J/TH',
    media: { type: 'image', src: '/images/products/whatsminer-m66s-280-322th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Whatsminer M66S+ 280 - 322 TH/s is a SHA-256 ASIC miner rated at 280 - 322 TH/s with listed power of 4760 - 5474 W. Estimated availability: SZ Stock. Listed hashrate reflects the supplier\'s 280 - 322 TH/s bin; the exact unit supplied will be confirmed before dispatch. Pricing may run up to $3,286 depending on the exact unit supplied. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M66S+ 280 - 322 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Whatsminer M66S+ 280 - 322 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Whatsminer M66S+ 280 - 322 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 69. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'bitdeer-a2-pro-258th',
    title: 'Bitdeer A2 Pro 258 TH/s',
    tag: 'BITDEER',
    price: '$3,993',
    priceUsd: 3993,
    hashrate: '258 TH/s',
    hashrateValue: 258,
    hashrateHz: 258000000000000,
    power: '3844 W',
    powerValue: 3844.2,
    efficiency: '14.9 J/TH',
    media: { type: 'image', src: '/images/products/bitdeer-a2-pro-258th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitdeer',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Bitdeer A2 Pro 258 TH/s is a SHA-256 ASIC miner rated at 258 TH/s with listed power of 3844 W. Estimated availability: 4 days HK. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitdeer',
      model: 'Bitdeer A2 Pro 258 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Bitdeer A2 Pro 258 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Bitdeer A2 Pro 258 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 77. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'bitdeer-a3-hydro-550th',
    title: 'Bitdeer A3 Hydro 550 TH/s',
    tag: 'BITDEER',
    price: '$8,040',
    priceUsd: 8040,
    hashrate: '550 TH/s',
    hashrateValue: 550,
    hashrateHz: 550000000000000,
    power: '7425 W',
    powerValue: 7425,
    efficiency: '13.5 J/TH',
    media: { type: 'image', src: '/images/products/bitdeer-a3-hydro-550th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitdeer',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Bitdeer A3 Hydro 550 TH/s is a SHA-256 ASIC miner rated at 550 TH/s with listed power of 7425 W. Estimated availability: 4 days HK. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitdeer',
      model: 'Bitdeer A3 Hydro 550 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Bitdeer A3 Hydro 550 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Bitdeer A3 Hydro 550 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 78. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'canaan-a15-pro-no-warranty-215th',
    title: 'Canaan A15 Pro (No warranty) 215 TH/s',
    tag: 'CANAAN',
    price: '$2,011',
    priceUsd: 2011,
    hashrate: '215 TH/s',
    hashrateValue: 215,
    hashrateHz: 215000000000000,
    power: '3612 W',
    powerValue: 3612,
    efficiency: '16.8 J/TH',
    media: { type: 'image', src: '/images/products/canaan-a15-pro-no-warranty-215th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Canaan',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Canaan A15 Pro (No warranty) 215 TH/s is a SHA-256 ASIC miner rated at 215 TH/s with listed power of 3612 W. Estimated availability: HK Stock. Sold without manufacturer warranty. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Canaan',
      model: 'Canaan A15 Pro (No warranty) 215 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Canaan A15 Pro (No warranty) 215 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Canaan A15 Pro (No warranty) 215 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 81. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'canaan-a1566-eha-424th',
    title: 'Canaan A1566 eHA 424 TH/s',
    tag: 'CANAAN',
    price: '$2,866',
    priceUsd: 2866,
    hashrate: '424 TH/s',
    hashrateValue: 424,
    hashrateHz: 424000000000000,
    power: '8268 W',
    powerValue: 8268,
    efficiency: '19.5 J/TH',
    media: { type: 'image', src: '/images/products/canaan-a1566-eha-424th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Canaan',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Canaan A1566 eHA 424 TH/s is a SHA-256 ASIC miner rated at 424 TH/s with listed power of 8268 W. Estimated availability: 12 days HK. Minimum order quantity: 5 units. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Canaan',
      model: 'Canaan A1566 eHA 424 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Canaan A1566 eHA 424 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Canaan A1566 eHA 424 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 84. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified. NOTE: source image 56.png was missing at build time; reused row 57\'s image (same Canaan A1566 family) as a placeholder — replace with the correct photo when available.',
  },
  {
    slug: 'canaan-a1566-ha-460th',
    title: 'Canaan A1566 HA 460 TH/s',
    tag: 'CANAAN',
    price: '$4,128',
    priceUsd: 4128,
    hashrate: '460 TH/s',
    hashrateValue: 460,
    hashrateHz: 460000000000000,
    power: '8188 W',
    powerValue: 8188,
    efficiency: '17.8 J/TH',
    media: { type: 'image', src: '/images/products/canaan-a1566-ha-460th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Canaan',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Canaan A1566 HA 460 TH/s is a SHA-256 ASIC miner rated at 460 TH/s with listed power of 8188 W. Estimated availability: 12 days HK. Minimum order quantity: 5 units. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Canaan',
      model: 'Canaan A1566 HA 460 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Canaan A1566 HA 460 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Canaan A1566 HA 460 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 85. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'canaan-a1566-ha-500th',
    title: 'Canaan A1566 HA 500 TH/s',
    tag: 'CANAAN',
    price: '$4,900',
    priceUsd: 4900,
    hashrate: '500 TH/s',
    hashrateValue: 500,
    hashrateHz: 500000000000000,
    power: '8400 W',
    powerValue: 8400,
    efficiency: '16.8 J/TH',
    media: { type: 'image', src: '/images/products/canaan-a1566-ha-500th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Canaan',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Canaan A1566 HA 500 TH/s is a SHA-256 ASIC miner rated at 500 TH/s with listed power of 8400 W. Estimated availability: 12 days HK. Minimum order quantity: 5 units. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Canaan',
      model: 'Canaan A1566 HA 500 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Canaan A1566 HA 500 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Canaan A1566 HA 500 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 86. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'canaan-avalon-mini-3-37-5th',
    title: 'Canaan Avalon Mini 3 37.5 TH/s',
    tag: 'CANAAN',
    price: '$1,820',
    priceUsd: 1820,
    hashrate: '37.5 TH/s',
    hashrateValue: 37.5,
    hashrateHz: 37500000000000,
    power: '800 W',
    powerValue: 800,
    efficiency: '21.333 J/TH',
    media: { type: 'image', src: '/images/products/canaan-avalon-mini-3-37-5th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Canaan',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Canaan Avalon Mini 3 37.5 TH/s is a SHA-256 ASIC miner rated at 37.5 TH/s with listed power of 800 W. Estimated availability: HK Stock. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Canaan',
      model: 'Canaan Avalon Mini 3 37.5 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Canaan Avalon Mini 3 37.5 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Canaan Avalon Mini 3 37.5 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 87. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'canaan-avalon-q-90th',
    title: 'Canaan Avalon Q 90 TH/s',
    tag: 'CANAAN',
    price: '$2,370',
    priceUsd: 2370,
    hashrate: '90 TH/s',
    hashrateValue: 90,
    hashrateHz: 90000000000000,
    power: '1674 W',
    powerValue: 1674,
    efficiency: '18.6 J/TH',
    media: { type: 'image', src: '/images/products/canaan-avalon-q-90th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Canaan',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description: 'Canaan Avalon Q 90 TH/s is a SHA-256 ASIC miner rated at 90 TH/s with listed power of 1674 W. Estimated availability: HK Stock. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Canaan',
      model: 'Canaan Avalon Q 90 TH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Canaan Avalon Q 90 TH/s ASIC Miner | Qubite International',
    metaDescription: 'View Canaan Avalon Q 90 TH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 88. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
  {
    slug: 'elphapex-dg1-14gh',
    title: 'Elphapex DG1+ 14 GH/s',
    tag: 'ELPHAPEX',
    price: '$2,230',
    priceUsd: 2230,
    hashrate: '14 GH/s',
    hashrateValue: 14,
    hashrateHz: 14000000000,
    power: '3950 W',
    powerValue: 3950,
    efficiency: '282 J/GH',
    media: { type: 'image', src: '/images/products/elphapex-dg1-14gh.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Elphapex',
    algorithm: 'Scrypt',
    mineableCoins: [{ name: 'Dogecoin', ticker: 'DOGE' }, { name: 'Litecoin', ticker: 'LTC' }],
    description: 'Elphapex DG1+ 14 GH/s is a Scrypt ASIC miner rated at 14 GH/s with listed power of 3950 W. Estimated availability: HK Stock. Specifications, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Elphapex',
      model: 'Elphapex DG1+ 14 GH/s',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: null,
    seoTitle: 'Elphapex DG1+ 14 GH/s ASIC Miner | Qubite International',
    metaDescription: 'View Elphapex DG1+ 14 GH/s specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Sourced from BitMars "Selected Products" sheet (Website products tab), source row 98. Price is BitMars\' website price (minimum of the listed range), not raw EXW wholesale cost. Spec validation: supplier-listed; manufacturer specifications not independently verified.',
  },
]
export const products: Product[] = baseProducts.filter((product) => !product.needsReview)

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug)
}
