export type Category = 'Air Cooling Miners' | 'Hydro Cooling Miners' | 'Immersion Miners'
export type Brand = 'MicroBT' | 'Bitmain' | 'IceRiver' | 'Goldshell' | 'Pinecone'
export type Cooling = 'air' | 'hydro'

export interface Product {
  slug: string
  title: string
  tag: string
  price: string
  priceUsd: number | null
  status?: 'In Stock' | 'No Stock'
  hashrate: string
  hashrateValue: number | null
  // Hashrate normalized to hashes-per-second, used only for cross-unit sort
  // comparisons (TH/s, GH/s, MH/s, KH/s aren't directly comparable as raw numbers).
  hashrateHz: number | null
  power: string
  powerValue: number
  efficiency: string
  dailyProfit: string | null
  dailyProfitUsd: number | null
  payback: string | null
  media: { type: 'image' | 'video'; src: string }
  category: Category
  cooling: Cooling
  brand: Brand
  algorithm: string
  mineableCoins: { name: string; ticker: string }[]
  description: string
  specs: {
    manufacturer: string
    model: string
    release: string
    noiseLevel: string
    fans: string
    interface: string
    inputVoltage: string
    temperature: string
    humidity: string
  }
  dimensionsMm?: string | null
  weightKg?: number | null
  psuIncluded?: boolean | null
  sourceUrl?: string | null
  // Internal QA note from the developer upload sheet — not shown publicly.
  developerNote?: string
  seoTitle?: string
  metaDescription?: string
  // Set for rows the developer upload sheet explicitly marked "Do not upload"
  // (unresolved model/spec conflicts) — excluded from every public listing.
  needsReview?: boolean
}

export const baseProducts: Product[] = [
  // --- Developer-verified catalogue upload (qubite-developer-upload-rowwise.md) ---
  // Row order and field values match that sheet exactly. Price fields are
  // untouched "Enter Qubite price" placeholders in the source — kept as
  // "Contact for pricing" here. dailyProfit/payback are intentionally null:
  // no live coin-price assumption exists for most of these coins.

  {
    slug: 'ae-box-ii-54m',
    title: 'AE BOX II (54M)',
    tag: 'GOLDSHELL',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '54 MH/s',
    hashrateValue: 54,
    hashrateHz: 54e6,
    power: '530 W',
    powerValue: 530,
    efficiency: '9.815 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/ae-box-ii-54m.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Goldshell',
    algorithm: 'zkSNARK',
    mineableCoins: [{ name: 'Aleo', ticker: 'ALEO' }],
    description:
      'AE BOX II (54M) is a zkSNARK ASIC miner rated at 54 MH/s with listed power of 530 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Goldshell',
      model: 'AE BOX II (54M)',
      release: 'Not confirmed',
      noiseLevel: '35 dBA',
      fans: '1',
      interface: 'Ethernet',
      inputVoltage: '12 V DC',
      temperature: '0 to 35 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '171 x 198 x 96',
    weightKg: 2.54,
    sourceUrl: 'https://www.goldshell.com/product/goldshell-ae-box-ii/',
    seoTitle: 'AE BOX II (54M) ASIC Miner | Qubite International',
    metaDescription:
      'View AE BOX II (54M) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Official Goldshell specifications match. VERIFIED.',
  },
  {
    slug: 'ae-max-360m',
    title: 'AE Max (360M)',
    tag: 'GOLDSHELL',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '360 MH/s',
    hashrateValue: 360,
    hashrateHz: 360e6,
    power: '3300 W',
    powerValue: 3300,
    efficiency: '9.167 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/ae-max-360m.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Goldshell',
    algorithm: 'zkSNARK',
    mineableCoins: [{ name: 'Aleo', ticker: 'ALEO' }],
    description:
      'AE Max (360M) is a zkSNARK ASIC miner rated at 360 MH/s with listed power of 3300 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Goldshell',
      model: 'AE Max (360M)',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'AE Max (360M) ASIC Miner | Qubite International',
    metaDescription:
      'View AE Max (360M) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'ae1-lite-270m',
    title: 'AE1 Lite (270M)',
    tag: 'ICERIVER',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '270 MH/s',
    hashrateValue: 270,
    hashrateHz: 270e6,
    power: '500 W',
    powerValue: 500,
    efficiency: '1.852 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/ae1-lite-270m.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'IceRiver',
    algorithm: 'zkSNARK',
    mineableCoins: [{ name: 'Aleo', ticker: 'ALEO' }],
    description:
      'AE1 Lite (270M) is a zkSNARK ASIC miner rated at 270 MH/s with listed power of 500 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'IceRiver',
      model: 'AE1 Lite (270M)',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '100–240 V AC',
      temperature: '0 to 40 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '205 x 110 x 202',
    weightKg: 4.02,
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'AE1 Lite (270M) ASIC Miner | Qubite International',
    metaDescription:
      'View AE1 Lite (270M) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'MODEL CORRECTION REQUIRED — published anyway per request. ASIC Miner Value and IceRiver currently list AE1 Lite at 300 MH/s / 500 W. Replace this row with the 300 MH/s SKU unless a legacy 270 MH/s supplier datasheet is available.',
  },
  {
    slug: 'antminer-al1-16-6t',
    title: 'Antminer AL1 16.6T',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '16.6 TH/s',
    hashrateValue: 16.6,
    hashrateHz: 16.6e12,
    power: '3730 W',
    powerValue: 3730,
    efficiency: '224.699 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-al1-16-6t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Blake3',
    mineableCoins: [{ name: 'Alephium', ticker: 'ALPH' }],
    description:
      'Antminer AL1 16.6T is a Blake3 ASIC miner rated at 16.6 TH/s with listed power of 3730 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer AL1 16.6T',
      release: 'Jul 2024',
      noiseLevel: '75 dBA',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '220–277 V AC',
      temperature: '-20 to 40 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '430 x 195 x 290',
    weightKg: 16.5,
    sourceUrl: 'https://support.bitmain.com/hc/en-us/articles/35412695385881-ALPH-Miner-AL1-Specifications',
    seoTitle: 'Antminer AL1 16.6T ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer AL1 16.6T specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Official Bitmain AL1 Pro specifications match. VERIFIED.',
  },
  {
    slug: 'antminer-e9-2400m',
    title: 'Antminer E9 (2400M)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '2,400 MH/s',
    hashrateValue: 2400,
    hashrateHz: 2400e6,
    power: '1920 W',
    powerValue: 1920,
    efficiency: '0.8 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-e9-2400m.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'EtHash',
    mineableCoins: [{ name: 'Ethereum Classic', ticker: 'ETC' }],
    description:
      'Antminer E9 (2400M) is a EtHash ASIC miner rated at 2400 MH/s with listed power of 2013 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer E9 (2400M)',
      release: 'Jul 2022',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '200–240 V AC',
      temperature: '0 to 40 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '520 x 195.5 x 290',
    weightKg: 17.7,
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer E9 (2400M) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer E9 (2400M) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'POWER CORRECTION REQUIRED — published anyway per request. The standard E9 2400 MH/s listing is commonly specified at 1920 W, while the uploaded sheet states 2013 W. Confirm the exact label/firmware mode.',
  },
  {
    slug: 'antminer-e9-pro-3680m',
    title: 'Antminer E9 Pro (3680M)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '3,680 MH/s',
    hashrateValue: 3680,
    hashrateHz: 3680e6,
    power: '2200 W',
    powerValue: 2200,
    efficiency: '0.598 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-e9-pro-3680m.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'EtHash',
    mineableCoins: [{ name: 'Ethereum Classic', ticker: 'ETC' }],
    description:
      'Antminer E9 Pro (3680M) is a EtHash ASIC miner rated at 3680 MH/s with listed power of 2200 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer E9 Pro (3680M)',
      release: 'Feb 2023',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer E9 Pro (3680M) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer E9 Pro (3680M) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-ks3-8-2t',
    title: 'Antminer KS3 (8.2T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '8.2 TH/s',
    hashrateValue: 8.2,
    hashrateHz: 8.2e12,
    power: '3200 W',
    powerValue: 3200,
    efficiency: '390.244 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-ks3-8-2t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'KHeavyHash',
    mineableCoins: [{ name: 'Kaspa', ticker: 'KAS' }],
    description:
      'Antminer KS3 (8.2T) is a KHeavyHash ASIC miner rated at 8.2 TH/s with listed power of 3200 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer KS3 (8.2T)',
      release: 'Sep 2023',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer KS3 (8.2T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer KS3 (8.2T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-ks3-9-4t',
    title: 'Antminer KS3-9.4T',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '9.4 TH/s',
    hashrateValue: 9.4,
    hashrateHz: 9.4e12,
    power: '3500 W',
    powerValue: 3500,
    efficiency: '372.34 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-ks3-9-4t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'KHeavyHash',
    mineableCoins: [{ name: 'Kaspa', ticker: 'KAS' }],
    description:
      'Antminer KS3-9.4T is a KHeavyHash ASIC miner rated at 9.4 TH/s with listed power of 3500 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer KS3-9.4T',
      release: 'Sep 2023',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer KS3-9.4T ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer KS3-9.4T specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-ks5-pro-21t',
    title: 'Antminer KS5 Pro (21T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '21 TH/s',
    hashrateValue: 21,
    hashrateHz: 21e12,
    power: '3150 W',
    powerValue: 3150,
    efficiency: '150 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-ks5-pro-21t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'KHeavyHash',
    mineableCoins: [{ name: 'Kaspa', ticker: 'KAS' }],
    description:
      'Antminer KS5 Pro (21T) is a KHeavyHash ASIC miner rated at 21 TH/s with listed power of 3150 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer KS5 Pro (21T)',
      release: 'Mar 2024',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer KS5 Pro (21T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer KS5 Pro (21T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-l11-20g',
    title: 'Antminer L11 20G',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '20 GH/s',
    hashrateValue: 20,
    hashrateHz: 20e9,
    power: '3680 W',
    powerValue: 3680,
    efficiency: '184 J/GH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-l11-20g.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [
      { name: 'Dogecoin', ticker: 'DOGE' },
      { name: 'Litecoin', ticker: 'LTC' },
    ],
    description:
      'Antminer L11 20G is a Scrypt ASIC miner rated at 20 GH/s with listed power of 3680 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L11 20G',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer L11 20G ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer L11 20G specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-l7-9050m',
    title: 'Antminer L7 (9050M)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '9,050 MH/s',
    hashrateValue: 9050,
    hashrateHz: 9050e6,
    power: '3425 W',
    powerValue: 3425,
    efficiency: '0.378 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-l7-9050m.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [
      { name: 'Dogecoin', ticker: 'DOGE' },
      { name: 'Litecoin', ticker: 'LTC' },
    ],
    description:
      'Antminer L7 (9050M) is a Scrypt ASIC miner rated at 9050 MH/s with listed power of 3425 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L7 (9050M)',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer L7 (9050M) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer L7 (9050M) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-l7-9300m',
    title: 'Antminer L7 (9300M)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '9,300 MH/s',
    hashrateValue: 9300,
    hashrateHz: 9300e6,
    power: '3425 W',
    powerValue: 3425,
    efficiency: '0.368 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-l7-9300m.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [
      { name: 'Dogecoin', ticker: 'DOGE' },
      { name: 'Litecoin', ticker: 'LTC' },
    ],
    description:
      'Antminer L7 (9300M) is a Scrypt ASIC miner rated at 9300 MH/s with listed power of 3425 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L7 (9300M)',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer L7 (9300M) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer L7 (9300M) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-l7-9500m',
    title: 'Antminer L7 (9500M)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '9,500 MH/s',
    hashrateValue: 9500,
    hashrateHz: 9500e6,
    power: '3425 W',
    powerValue: 3425,
    efficiency: '0.361 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-l7-9500m.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [
      { name: 'Dogecoin', ticker: 'DOGE' },
      { name: 'Litecoin', ticker: 'LTC' },
    ],
    description:
      'Antminer L7 (9500M) is a Scrypt ASIC miner rated at 9500 MH/s with listed power of 3425 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L7 (9500M)',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer L7 (9500M) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer L7 (9500M) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-l9-15g',
    title: 'Antminer L9 15G',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '15 GH/s',
    hashrateValue: 15,
    hashrateHz: 15e9,
    power: '3150 W',
    powerValue: 3150,
    efficiency: '210 J/GH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-l9-15g.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [
      { name: 'Dogecoin', ticker: 'DOGE' },
      { name: 'Litecoin', ticker: 'LTC' },
    ],
    description:
      'Antminer L9 15G is a Scrypt ASIC miner rated at 15 GH/s with listed power of 3150 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L9 15G',
      release: 'Jun 2024',
      noiseLevel: '75 dBA',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '220–277 V AC',
      temperature: '-20 to 45 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '400 x 195 x 290',
    weightKg: 14.2,
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer L9 15G ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer L9 15G specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-l9-16g',
    title: 'Antminer L9 16G',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '16 GH/s',
    hashrateValue: 16,
    hashrateHz: 16e9,
    power: '3360 W',
    powerValue: 3360,
    efficiency: '210 J/GH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-l9-16g.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [
      { name: 'Dogecoin', ticker: 'DOGE' },
      { name: 'Litecoin', ticker: 'LTC' },
    ],
    description:
      'Antminer L9 16G is a Scrypt ASIC miner rated at 16 GH/s with listed power of 3360 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L9 16G',
      release: 'Jun 2024',
      noiseLevel: '75 dBA',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '220–277 V AC',
      temperature: '-20 to 45 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '400 x 195 x 290',
    weightKg: 14.2,
    sourceUrl: 'https://support.bitmain.com/hc/en-us/articles/33850555425305-L9-Specifications',
    seoTitle: 'Antminer L9 16G ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer L9 16G specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Official Bitmain specifications match. VERIFIED.',
  },
  {
    slug: 'antminer-l9-16-5g',
    title: 'Antminer L9 16.5G',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '16.5 GH/s',
    hashrateValue: 16.5,
    hashrateHz: 16.5e9,
    power: '3460 W',
    powerValue: 3460,
    efficiency: '209.697 J/GH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-l9-16-5g.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [
      { name: 'Dogecoin', ticker: 'DOGE' },
      { name: 'Litecoin', ticker: 'LTC' },
    ],
    description:
      'Antminer L9 16.5G is a Scrypt ASIC miner rated at 16.5 GH/s with listed power of 3460 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L9 16.5G',
      release: 'Jun 2024',
      noiseLevel: '75 dBA',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '220–277 V AC',
      temperature: '-20 to 45 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '400 x 195 x 290',
    weightKg: 14.2,
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer L9 16.5G ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer L9 16.5G specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-l9-17g',
    title: 'Antminer L9 17G',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '17 GH/s',
    hashrateValue: 17,
    hashrateHz: 17e9,
    power: '3570 W',
    powerValue: 3570,
    efficiency: '210 J/GH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-l9-17g.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Scrypt',
    mineableCoins: [
      { name: 'Dogecoin', ticker: 'DOGE' },
      { name: 'Litecoin', ticker: 'LTC' },
    ],
    description:
      'Antminer L9 17G is a Scrypt ASIC miner rated at 17 GH/s with listed power of 3570 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer L9 17G',
      release: 'Jun 2024',
      noiseLevel: '75 dBA',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '220–277 V AC',
      temperature: '-20 to 45 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '400 x 195 x 290',
    weightKg: 14.2,
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer L9 17G ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer L9 17G specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-s19-pro-100t',
    title: 'Antminer S19 Pro (100T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '100 TH/s',
    hashrateValue: 100,
    hashrateHz: 100e12,
    power: '3050 W',
    powerValue: 3050,
    efficiency: '30.5 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-s19-pro-100t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer S19 Pro (100T) is a SHA-256 ASIC miner rated at 100 TH/s with listed power of 3050 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19 Pro (100T)',
      release: 'May 2020',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '200–240 V AC',
      temperature: '0 to 40 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '370 x 195.5 x 290',
    weightKg: 13.2,
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer S19 Pro (100T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer S19 Pro (100T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-s19-pro-104t',
    title: 'Antminer S19 Pro (104T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '104 TH/s',
    hashrateValue: 104,
    hashrateHz: 104e12,
    power: '3068 W',
    powerValue: 3068,
    efficiency: '29.5 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-s19-pro-104t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer S19 Pro (104T) is a SHA-256 ASIC miner rated at 104 TH/s with listed power of 3068 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19 Pro (104T)',
      release: 'May 2020',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '200–240 V AC',
      temperature: '0 to 40 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '370 x 195.5 x 290',
    weightKg: 13.2,
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer S19 Pro (104T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer S19 Pro (104T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-s19-xp-141t',
    title: 'Antminer S19 XP (141T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '141 TH/s',
    hashrateValue: 141,
    hashrateHz: 141e12,
    power: '3010 W',
    powerValue: 3010,
    efficiency: '21.348 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-s19-xp-141t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer S19 XP (141T) is a SHA-256 ASIC miner rated at 141 TH/s with listed power of 3010 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19 XP (141T)',
      release: 'Jul 2022',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer S19 XP (141T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer S19 XP (141T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-s19j-pro-100t',
    title: 'Antminer S19j Pro (100T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '100 TH/s',
    hashrateValue: 100,
    hashrateHz: 100e12,
    power: '3050 W',
    powerValue: 3050,
    efficiency: '30.5 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-s19j-pro-100t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer S19j Pro (100T) is a SHA-256 ASIC miner rated at 100 TH/s with listed power of 3050 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19j Pro (100T)',
      release: 'Jul 2021',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '200–240 V AC',
      temperature: '0 to 40 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '370 x 195.5 x 290',
    weightKg: 13.2,
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer S19j Pro (100T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer S19j Pro (100T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-s19j-pro-104t',
    title: 'Antminer S19j Pro (104T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '104 TH/s',
    hashrateValue: 104,
    hashrateHz: 104e12,
    power: '3068 W',
    powerValue: 3068,
    efficiency: '29.5 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-s19j-pro-104t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer S19j Pro (104T) is a SHA-256 ASIC miner rated at 104 TH/s with listed power of 3068 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19j Pro (104T)',
      release: 'Jul 2021',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '200–240 V AC',
      temperature: '0 to 40 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '370 x 195.5 x 290',
    weightKg: 13.2,
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer S19j Pro (104T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer S19j Pro (104T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-s19j-pro-120t',
    title: 'Antminer S19j Pro+ (120T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '120 TH/s',
    hashrateValue: 120,
    hashrateHz: 120e12,
    power: '3300 W',
    powerValue: 3300,
    efficiency: '27.5 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-s19j-pro-120t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer S19j Pro+ (120T) is a SHA-256 ASIC miner rated at 120 TH/s with listed power of 3300 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S19j Pro+ (120T)',
      release: 'Jul 2021',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '200–240 V AC',
      temperature: '0 to 40 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '370 x 195.5 x 290',
    weightKg: 13.2,
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer S19j Pro+ (120T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer S19j Pro+ (120T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-s21-195t',
    title: 'Antminer S21 (195T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '195 TH/s',
    hashrateValue: 195,
    hashrateHz: 195e12,
    power: '3500 W',
    powerValue: 3500,
    efficiency: '17.949 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-s21-195t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer S21 (195T) is a SHA-256 ASIC miner rated at 195 TH/s with listed power of 3500 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21 (195T)',
      release: 'Oct 2023',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '220–277 V AC',
      temperature: '0 to 45 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '400 x 195 x 290',
    weightKg: 15.4,
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer S21 (195T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer S21 (195T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-s21-200t',
    title: 'Antminer S21 (200T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '200 TH/s',
    hashrateValue: 200,
    hashrateHz: 200e12,
    power: '3550 W',
    powerValue: 3550,
    efficiency: '17.75 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-s21-200t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer S21 (200T) is a SHA-256 ASIC miner rated at 200 TH/s with listed power of 3550 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21 (200T)',
      release: 'Oct 2023',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '220–277 V AC',
      temperature: '0 to 45 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '400 x 195 x 290',
    weightKg: 15.4,
    sourceUrl: 'https://support.bitmain.com/hc/en-us/articles/23794895251609-S21-Specification',
    seoTitle: 'Antminer S21 (200T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer S21 (200T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Official Bitmain specifications match. VERIFIED.',
  },
  {
    slug: 'antminer-s21-pro-234t',
    title: 'Antminer S21 Pro (234T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '234 TH/s',
    hashrateValue: 234,
    hashrateHz: 234e12,
    power: '3510 W',
    powerValue: 3510,
    efficiency: '15 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-s21-pro-234t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer S21 Pro (234T) is a SHA-256 ASIC miner rated at 234 TH/s with listed power of 3510 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21 Pro (234T)',
      release: 'Apr 2024',
      noiseLevel: '76 dBA',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '220–277 V AC',
      temperature: '-20 to 45 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '450 x 219 x 293',
    weightKg: 20,
    sourceUrl: 'https://support.bitmain.com/hc/en-us/articles/31321354157593-S21-Pro-Specification',
    seoTitle: 'Antminer S21 Pro (234T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer S21 Pro (234T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Official Bitmain specifications match. VERIFIED.',
  },
  {
    slug: 'antminer-s21-pro-245th',
    title: 'Antminer S21 PRO (245Th)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '245 TH/s',
    hashrateValue: 245,
    hashrateHz: 245e12,
    power: '3510 W',
    powerValue: 3510,
    efficiency: '14.327 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-s21-pro-245th.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer S21 PRO (245Th) is a SHA-256 ASIC miner rated at 245 TH/s with listed power of 3510 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21 PRO (245Th)',
      release: 'Apr 2024',
      noiseLevel: '76 dBA',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '220–277 V AC',
      temperature: '-20 to 45 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '450 x 219 x 293',
    weightKg: 20,
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer S21 PRO (245Th) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer S21 PRO (245Th) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'BATCH DATASHEET REQUIRED — published anyway per request. This 245 TH/s row reuses the official 234 TH/s S21 Pro dimensions/power claim without the exact 245 TH/s batch datasheet confirmed.',
  },
  {
    slug: 'antminer-s21-xp-270t',
    title: 'Antminer S21 XP (270T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '270 TH/s',
    hashrateValue: 270,
    hashrateHz: 270e12,
    power: '3645 W',
    powerValue: 3645,
    efficiency: '13.5 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-s21-xp-270t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer S21 XP (270T) is a SHA-256 ASIC miner rated at 270 TH/s with listed power of 3645 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21 XP (270T)',
      release: 'Jul 2024',
      noiseLevel: '76 dBA',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '220–277 V AC',
      temperature: '-20 to 45 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '449 x 219 x 293',
    weightKg: 18.7,
    sourceUrl: 'https://support.bitmain.com/hc/en-us/articles/35383015643673-S21-XP-Specifications',
    seoTitle: 'Antminer S21 XP (270T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer S21 XP (270T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Official Bitmain specifications match. VERIFIED.',
  },
  {
    slug: 'antminer-s21-xp-hydro-473t',
    title: 'Antminer S21 XP Hydro (473T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '473 TH/s',
    hashrateValue: 473,
    hashrateHz: 473e12,
    power: '5676 W',
    powerValue: 5676,
    efficiency: '12 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-s21-xp-hydro-473t.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer S21 XP Hydro (473T) is a SHA-256 ASIC miner rated at 473 TH/s with listed power of 5676 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21 XP Hydro (473T)',
      release: 'Nov 2024',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '380–415 V AC',
      temperature: 'Coolant-specific °C',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer S21 XP Hydro (473T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer S21 XP Hydro (473T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-s21-216t',
    title: 'Antminer S21+ (216T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '216 TH/s',
    hashrateValue: 216,
    hashrateHz: 216e12,
    power: '3564 W',
    powerValue: 3564,
    efficiency: '16.5 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-s21-216t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer S21+ (216T) is a SHA-256 ASIC miner rated at 216 TH/s with listed power of 3564 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21+ (216T)',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer S21+ (216T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer S21+ (216T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-s21-hyd-338t',
    title: 'Antminer S21+ Hyd (338T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '338 TH/s',
    hashrateValue: 338,
    hashrateHz: 338e12,
    power: '5070 W',
    powerValue: 5070,
    efficiency: '15 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-s21-hyd-338t.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer S21+ Hyd (338T) is a SHA-256 ASIC miner rated at 338 TH/s with listed power of 5070 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21+ Hyd (338T)',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '380–415 V AC',
      temperature: 'Coolant-specific °C',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer S21+ Hyd (338T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer S21+ Hyd (338T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-s21-hydro-358t',
    title: 'Antminer S21+ Hydro (358T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '358 TH/s',
    hashrateValue: 358,
    hashrateHz: 358e12,
    power: '5370 W',
    powerValue: 5370,
    efficiency: '15 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-s21-hydro-358t.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer S21+ Hydro (358T) is a SHA-256 ASIC miner rated at 358 TH/s with listed power of 5370 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21+ Hydro (358T)',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '380–415 V AC',
      temperature: 'Coolant-specific °C',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer S21+ Hydro (358T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer S21+ Hydro (358T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-t21-190t',
    title: 'Antminer T21 (190T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '190 TH/s',
    hashrateValue: 190,
    hashrateHz: 190e12,
    power: '3610 W',
    powerValue: 3610,
    efficiency: '19 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-t21-190t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer T21 (190T) is a SHA-256 ASIC miner rated at 190 TH/s with listed power of 3610 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer T21 (190T)',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer T21 (190T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer T21 (190T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-z15-pro-840k',
    title: 'Antminer Z15 Pro 840K',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '840 KH/s',
    hashrateValue: 840,
    hashrateHz: 840e3,
    power: '2780 W',
    powerValue: 2780,
    efficiency: '3.31 J/KH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-z15-pro-840k.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'Equihash',
    mineableCoins: [{ name: 'Zcash', ticker: 'ZEC' }],
    description:
      'Antminer Z15 Pro 840K is a Equihash ASIC miner rated at 840 KH/s with listed power of 2780 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer Z15 Pro 840K',
      release: 'Jun 2023',
      noiseLevel: 'Not confirmed',
      fans: '2',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer Z15 Pro 840K ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer Z15 Pro 840K specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'bitmain-antminer-s21-hyd-395th',
    title: 'Bitmain Antminer S21+ Hyd (395Th)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '395 TH/s',
    hashrateValue: 395,
    hashrateHz: 395e12,
    power: '5950 W',
    powerValue: 5950,
    efficiency: '15.063 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/bitmain-antminer-s21-hyd-395th.webp' },
    category: 'Hydro Cooling Miners',
    cooling: 'hydro',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Bitmain Antminer S21+ Hyd (395Th) is a SHA-256 ASIC miner rated at 395 TH/s with listed power of 5950 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Bitmain Antminer S21+ Hyd (395Th)',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '380–415 V AC',
      temperature: 'Coolant-specific °C',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Bitmain Antminer S21+ Hyd (395Th) ASIC Miner | Qubite International',
    metaDescription:
      'View Bitmain Antminer S21+ Hyd (395Th) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'goldshell-ae-max-360m',
    title: 'Goldshell AE Max (360M)',
    tag: 'GOLDSHELL',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '360 MH/s',
    hashrateValue: 360,
    hashrateHz: 360e6,
    power: '3300 W',
    powerValue: 3300,
    efficiency: '9.167 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/goldshell-ae-max-360m.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Goldshell',
    algorithm: 'zkSNARK',
    mineableCoins: [{ name: 'Aleo', ticker: 'ALEO' }],
    description:
      'Goldshell AE Max (360M) is a zkSNARK ASIC miner rated at 360 MH/s with listed power of 3300 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Goldshell',
      model: 'Goldshell AE Max (360M)',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Goldshell AE Max (360M) ASIC Miner | Qubite International',
    metaDescription:
      'View Goldshell AE Max (360M) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'iceriver-ae1-lite-300m',
    title: 'IceRiver AE1 Lite (300M)',
    tag: 'ICERIVER',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '300 MH/s',
    hashrateValue: 300,
    hashrateHz: 300e6,
    power: '500 W',
    powerValue: 500,
    efficiency: '1.667 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/iceriver-ae1-lite-300m.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'IceRiver',
    algorithm: 'zkSNARK',
    mineableCoins: [{ name: 'Aleo', ticker: 'ALEO' }],
    description:
      'IceRiver AE1 Lite (300M) is a zkSNARK ASIC miner rated at 300 MH/s with listed power of 500 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'IceRiver',
      model: 'AE1 Lite (300M)',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '100–240 V AC',
      temperature: '0 to 40 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '205 x 110 x 202',
    weightKg: 4.02,
    sourceUrl: 'https://www.iceriver.io/product/iceriver-aleo-ae1-lite/',
    seoTitle: 'IceRiver AE1 Lite (300M) ASIC Miner | Qubite International',
    metaDescription:
      'View IceRiver AE1 Lite (300M) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Official IceRiver specifications match. VERIFIED.',
  },
  {
    slug: 'iceriver-al3-15t',
    title: 'IceRiver AL3 15T',
    tag: 'ICERIVER',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '15 TH/s',
    hashrateValue: 15,
    hashrateHz: 15e12,
    power: '3500 W',
    powerValue: 3500,
    efficiency: '233.333 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/iceriver-al3-15t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'IceRiver',
    algorithm: 'Blake3',
    mineableCoins: [{ name: 'Alephium', ticker: 'ALPH' }],
    description:
      'IceRiver AL3 15T is a Blake3 ASIC miner rated at 15 TH/s with listed power of 3500 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'IceRiver',
      model: 'AL3 15T',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Confirm supplier',
      temperature: '0 to 35 °C',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.iceriver.io/product-category/all-product/',
    seoTitle: 'IceRiver AL3 15T ASIC Miner | Qubite International',
    metaDescription:
      'View IceRiver AL3 15T specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'VERIFIED CORE. Official IceRiver catalogue confirms 15 TH/s / 3500 W; confirm physical details.',
  },
  {
    slug: 'iceriver-ks3l-5t',
    title: 'IceRiver KS3L (5T)',
    tag: 'ICERIVER',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '5 TH/s',
    hashrateValue: 5,
    hashrateHz: 5e12,
    power: '3180 W',
    powerValue: 3180,
    efficiency: '636 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/iceriver-ks3l-5t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'IceRiver',
    algorithm: 'KHeavyHash',
    mineableCoins: [{ name: 'Kaspa', ticker: 'KAS' }],
    description:
      'IceRiver KS3L (5T) is a KHeavyHash ASIC miner rated at 5 TH/s with listed power of 3180 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'IceRiver',
      model: 'KS3L (5T)',
      release: 'Sep 2023',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'IceRiver KS3L (5T) ASIC Miner | Qubite International',
    metaDescription:
      'View IceRiver KS3L (5T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'ks3m-6t',
    title: 'KS3M (6T)',
    tag: 'ICERIVER',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '6 TH/s',
    hashrateValue: 6,
    hashrateHz: 6e12,
    power: '3400 W',
    powerValue: 3400,
    efficiency: '566.7 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/ks3m-6t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'IceRiver',
    algorithm: 'KHeavyHash',
    mineableCoins: [{ name: 'Kaspa', ticker: 'KAS' }],
    description:
      'KS3M (6T) is a KHeavyHash ASIC miner rated at 6 TH/s with listed power of 3400 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'IceRiver',
      model: 'KS3M (6T)',
      release: 'Sep 2023',
      noiseLevel: '75 dBA',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '170–300 V AC',
      temperature: '0 to 35 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '370 x 195 x 290',
    weightKg: 14.4,
    sourceUrl: 'https://www.iceriver.io/product/iceriver-ks3m/',
    seoTitle: 'KS3M (6T) ASIC Miner | Qubite International',
    metaDescription:
      'View KS3M (6T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'CORRECTED 2026-09: sheet listed hashrate as "3 MH/s", conflicting with its own "(6T)" title. Cross-verified against ASIC Miner Value, Zeus Mining, and other independent retailer listings — official spec is 6 TH/s @ 3400W (566.7 J/TH).',
  },
  {
    slug: 'ks5m-15t',
    title: 'KS5M (15T)',
    tag: 'ICERIVER',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '15 TH/s',
    hashrateValue: 15,
    hashrateHz: 15e12,
    power: '3400 W',
    powerValue: 3400,
    efficiency: '226.7 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/ks5m-15t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'IceRiver',
    algorithm: 'KHeavyHash',
    mineableCoins: [{ name: 'Kaspa', ticker: 'KAS' }],
    description:
      'KS5M (15T) is a KHeavyHash ASIC miner rated at 15 TH/s with listed power of 3400 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'IceRiver',
      model: 'KS5M (15T)',
      release: 'Mar 2024',
      noiseLevel: '75 dBA',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '170–300 V AC',
      temperature: '0 to 35 °C',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '430 x 195 x 290',
    weightKg: 15.5,
    sourceUrl: 'https://www.iceriver.io/product/kas-ks5m-hostingkrc20-limited-edition/',
    seoTitle: 'KS5M (15T) ASIC Miner | Qubite International',
    metaDescription:
      'View KS5M (15T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'CORRECTED 2026-09: sheet listed hashrate as "5 MH/s", conflicting with its own "(15T)" title. Cross-verified against ASIC Miner Value, Zeus Mining, and other independent retailer listings — official spec is 15 TH/s @ 3400W (226.7 J/TH).',
  },
  {
    slug: 'antminer-s21-235t',
    title: 'Antminer S21+ (235T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '235 TH/s',
    hashrateValue: 235,
    hashrateHz: 235e12,
    power: '3870 W',
    powerValue: 3870,
    efficiency: '16.468 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-s21-235t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Antminer S21+ (235T) is a SHA-256 ASIC miner rated at 235 TH/s with listed power of 3870 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer S21+ (235T)',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Antminer S21+ (235T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer S21+ (235T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'iceriver-ae2-720m',
    title: 'IceRiver AE2 720m',
    tag: 'ICERIVER',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '720 MH/s',
    hashrateValue: 720,
    hashrateHz: 720e6,
    power: '1300 W',
    powerValue: 1300,
    efficiency: '1.806 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/iceriver-ae2-720m.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'IceRiver',
    algorithm: 'zkSNARK',
    mineableCoins: [{ name: 'Aleo', ticker: 'ALEO' }],
    description:
      'IceRiver AE2 720m is a zkSNARK ASIC miner rated at 720 MH/s with listed power of 1300 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'IceRiver',
      model: 'AE2 720m',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'IceRiver AE2 720m ASIC Miner | Qubite International',
    metaDescription:
      'View IceRiver AE2 720m specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'whatsminer-m60',
    title: 'Whatsminer M60',
    tag: 'MICROBT',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: 'Unverified',
    hashrateValue: null,
    hashrateHz: null,
    power: '3440 W',
    powerValue: 3440,
    efficiency: 'Not confirmed',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/whatsminer-m60.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'MicroBT',
    algorithm: 'SHA-256',
    mineableCoins: [{ name: 'Bitcoin', ticker: 'BTC' }],
    description:
      'Whatsminer M60 is a SHA-256 ASIC miner rated at supplier-confirmed hashrate with listed power of 3440 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'MicroBT',
      model: 'Whatsminer M60',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Whatsminer M60 ASIC Miner | Qubite International',
    metaDescription:
      'View Whatsminer M60 specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'HASHRATE VARIANT REQUIRED — published anyway per request, hashrate left unset rather than guessed. M60 is a product family with multiple hashrate bins; add the exact TH/s model from the machine label or supplier invoice when known.',
  },
  {
    slug: 'pinecone-matches-inibox-850m',
    title: 'Pinecone Matches INIBOX (850M)',
    tag: 'PINECONE',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '850 MH/s',
    hashrateValue: 850,
    hashrateHz: 850e6,
    power: '500 W',
    powerValue: 500,
    efficiency: '0.588 J/MH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/pinecone-matches-inibox-850m.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Pinecone',
    algorithm: 'VersaHash',
    mineableCoins: [{ name: 'InitVerse', ticker: 'INI' }],
    description:
      'Pinecone Matches INIBOX (850M) is a VersaHash ASIC miner rated at 850 MH/s with listed power of 500 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Pinecone',
      model: 'Matches INIBOX (850M)',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Pinecone Matches INIBOX (850M) ASIC Miner | Qubite International',
    metaDescription:
      'View Pinecone Matches INIBOX (850M) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'pinecone-matches-inibox-pro-2-4g',
    title: 'Pinecone Matches INIBOX Pro (2.4G)',
    tag: 'PINECONE',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '2.4 GH/s',
    hashrateValue: 2.4,
    hashrateHz: 2.4e9,
    power: '1280 W',
    powerValue: 1280,
    efficiency: '533.333 J/GH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/pinecone-matches-inibox-pro-2-4g.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Pinecone',
    algorithm: 'VersaHash',
    mineableCoins: [{ name: 'InitVerse', ticker: 'INI' }],
    description:
      'Pinecone Matches INIBOX Pro (2.4G) is a VersaHash ASIC miner rated at 2.4 GH/s with listed power of 1280 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Pinecone',
      model: 'Matches INIBOX Pro (2.4G)',
      release: 'Not confirmed',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: 'Not confirmed',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    sourceUrl: 'https://www.asicminervalue.com/',
    seoTitle: 'Pinecone Matches INIBOX Pro (2.4G) ASIC Miner | Qubite International',
    metaDescription:
      'View Pinecone Matches INIBOX Pro (2.4G) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote:
      'SECONDARY-SOURCE MATCH via ASIC Miner Value. Profit, revenue, ROI and live marketplace price intentionally excluded.',
  },
  {
    slug: 'antminer-ks5-20t',
    title: 'Antminer KS5 (20T)',
    tag: 'BITMAIN',
    price: 'Contact for pricing',
    priceUsd: null,
    hashrate: '20 TH/s',
    hashrateValue: 20,
    hashrateHz: 20e12,
    power: '3000 W',
    powerValue: 3000,
    efficiency: '150 J/TH',
    dailyProfit: null,
    dailyProfitUsd: null,
    payback: null,
    media: { type: 'image', src: '/images/products/antminer-ks5-20t.webp' },
    category: 'Air Cooling Miners',
    cooling: 'air',
    brand: 'Bitmain',
    algorithm: 'KHeavyHash',
    mineableCoins: [{ name: 'Kaspa', ticker: 'KAS' }],
    description:
      'Antminer KS5 (20T) is a KHeavyHash ASIC miner rated at 20 TH/s with listed power of 3000 W. Availability, condition, warranty and electrical requirements must be confirmed in the quotation.',
    specs: {
      manufacturer: 'Bitmain',
      model: 'Antminer KS5 (20T)',
      release: 'Mar 2024',
      noiseLevel: 'Not confirmed',
      fans: 'Not confirmed',
      interface: 'Ethernet',
      inputVoltage: '220–277 V AC',
      temperature: 'Not confirmed',
      humidity: 'Not confirmed',
    },
    dimensionsMm: '400 x 195 x 290',
    weightKg: 15.8,
    sourceUrl: 'https://support.bitmain.com/hc/en-us/articles/29471533336345-KS5-Specifications',
    seoTitle: 'Antminer KS5 (20T) ASIC Miner | Qubite International',
    metaDescription:
      'View Antminer KS5 (20T) specifications, electrical requirements and availability. Request current UAE pricing and hosting options.',
    developerNote: 'Official Bitmain core specifications match. VERIFIED CORE.',
  },
]

export const products: Product[] = baseProducts.filter((product) => !product.needsReview)

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug)
}
